\set ON_ERROR_STOP
--
-- 患者レセプト分割テーブル
--
-- Create Date : 2012/12/17         --
--
create	table	tbl_pt_hdist_day	(
	HOSPNUM         smallint NOT NULL,
	PTID		bigint,
	NYUGAIKBN	char(1) NOT NULL,
	SRYYM	   	char(6) NOT NULL,
	DAY  		char(2) NOT NULL,
	RECEIPT_KBN	char(1) NOT NULL,
	HKNCOMBI1_1	smallint DEFAULT 0,
	HKNCOMBI1_2	smallint DEFAULT 0,
	HKNCOMBI1_3	smallint DEFAULT 0,
	HKNCOMBI1_4	smallint DEFAULT 0,
	HKNCOMBI1_5	smallint DEFAULT 0,
	HKNCOMBI1_6	smallint DEFAULT 0,
	HKNCOMBI1_7	smallint DEFAULT 0,
	HKNCOMBI1_8	smallint DEFAULT 0,
	HKNCOMBI1_9	smallint DEFAULT 0,
	HKNCOMBI1_10	smallint DEFAULT 0,
	HKNCOMBI1_11	smallint DEFAULT 0,
	HKNCOMBI1_12	smallint DEFAULT 0,
	HKNCOMBI1_13	smallint DEFAULT 0,
	HKNCOMBI1_14	smallint DEFAULT 0,
	HKNCOMBI1_15	smallint DEFAULT 0,
	HKNCOMBI1_16	smallint DEFAULT 0,
	HKNCOMBI1_17	smallint DEFAULT 0,
	HKNCOMBI1_18	smallint DEFAULT 0,
	HKNCOMBI1_19	smallint DEFAULT 0,
	HKNCOMBI1_20	smallint DEFAULT 0,
	HKNCOMBI2_1	smallint DEFAULT 0,
	HKNCOMBI2_2	smallint DEFAULT 0,
	HKNCOMBI2_3	smallint DEFAULT 0,
	HKNCOMBI2_4	smallint DEFAULT 0,
	HKNCOMBI2_5	smallint DEFAULT 0,
	HKNCOMBI2_6	smallint DEFAULT 0,
	HKNCOMBI2_7	smallint DEFAULT 0,
	HKNCOMBI2_8	smallint DEFAULT 0,
	HKNCOMBI2_9	smallint DEFAULT 0,
	HKNCOMBI2_10	smallint DEFAULT 0,
	HKNCOMBI2_11	smallint DEFAULT 0,
	HKNCOMBI2_12	smallint DEFAULT 0,
	HKNCOMBI2_13	smallint DEFAULT 0,
	HKNCOMBI2_14	smallint DEFAULT 0,
	HKNCOMBI2_15	smallint DEFAULT 0,
	HKNCOMBI2_16	smallint DEFAULT 0,
	HKNCOMBI2_17	smallint DEFAULT 0,
	HKNCOMBI2_18	smallint DEFAULT 0,
	HKNCOMBI2_19	smallint DEFAULT 0,
	HKNCOMBI2_20	smallint DEFAULT 0,
	TERMID		varchar(16),
	OPID		varchar(16),
	CREYMD		char(8),
	UPYMD		char(8),
	UPHMS		char(6),
	Constraint "tbl_pt_hdist_day_key" primary	key(
		HOSPNUM,
		PTID,
		NYUGAIKBN,
		SRYYM,
		DAY,
		RECEIPT_KBN
	)
);
