OBJS = ORCGP014.so   ORCGP02.so   ORCGP020.so   ORCGP0201.so   ORCGP021.so \
       ORCGP023.so   ORCGP024.so  ORCGP025.so   ORCGP027.so \
       ORCGP029.so   ORCGP02A.so  ORCGP02W1.so  ORCGP02E.so    ORCGP02F.so \
       ORCGP02W2.so  ORCGP02W3.so ORCGP98.so    ORCGP981.so    ORCGP99.so \
       ORCGPERR.so   ORCGPID1.so  ORCSADR.so    ORCSP01.so     ORCSP02.so \
       ORCGP982.so   ORCGP02D.so  ORCGP100.so   ORCSP03A.so    ORCSP03B.so

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global
