SRCS = ORCGI01.CBL \
       ORCGI02.CBL \
       ORCGI03.CBL \
       ORCGI04.CBL \
       ORCGI0ERR.CBL \
       ORCGI0ID1.CBL \
       ORCGI0SUB01.CBL 

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

