SRCS = ORCGX01.CBL \
       ORCGX02.CBL \
       ORCGX91.CBL \
       ORCGX97.CBL \
       ORCGX98.CBL \
       ORCGXERR.CBL \
       ORCGXID1.CBL \
       ORCGXID2.CBL \
       ORCHXLST.CBL

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

