SRCS = ORCGG01.CBL \
       ORCGG99.CBL \
       ORCGGERR.CBL \
       ORCGGID1.CBL \
       ORCGGID2.CBL \
       ORCGG02.CBL \
       ORCGG03.CBL \
       ORCGG05.CBL \


top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

