OBJS = ORCGJ02.so   ORCGJ021.so   ORCGJ022.so   ORCGJ03.so \
       ORCGJ04.so   ORCGJ041.so   ORCGJ042.so   ORCGJ98.so    ORCGJ99.so \
       ORCGJERR.so  ORCGJID1.so   ORCGJ023.so   ORCGJ024.so

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

