SRCS = ORCGS02.CBL \
       ORCGS03.CBL \
       ORCGS04.CBL \
       ORCGS06.CBL \
       ORCGS07.CBL \
       ORCGS08.CBL \
       ORCGS09.CBL \
       ORCGS10.CBL \
       ORCGS99.CBL \
       ORCGSERR.CBL \
       ORCGSID1.CBL \
       ORCGSID2.CBL \
       ORCGSID3.CBL \
       ORCGSID4.CBL \
       ORCGSSUB01.CBL \
       ORCGSSUB02.CBL \
       ORCGSSUB03.CBL \
       ORCGSDMY01.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

