SRCS = ORCGS02.CBL \
       ORCGS03.CBL \
       ORCGS03N.CBL \
       ORCGS04.CBL \
       ORCGS05.CBL \
       ORCGSERR.CBL \
       ORCGSID1.CBL 

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

