OBJS = ORCGQ01.so  ORCGQ02.so  ORCGQ98.so  ORCGQ99.so \
       ORCGQERR.so ORCGQID1.so ORCGQSUB01.so ORCGQ97.so \
       ORCGQ100.so

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global
