SRCS = ORCGQ01.CBL \
       ORCGQ02.CBL \
       ORCGQ02A.CBL \
       ORCGQ02B.CBL \
       ORCGQ03.CBL \
       ORCGQ98.CBL \
       ORCGQ99.CBL \
       ORCGQERR.CBL \
       ORCGQID1.CBL \
       ORCGQSUB01.CBL \
       ORCGQSUB02.CBL \
       ORCGQ97.CBL \
       ORCGQ100.CBL \
       ORCGQ96.CBL \
       ORCGQ04.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

