CSRCS = \
	orcfiledel.c \
	orcfileio.c \
	cobabort.c \
	coblog.c \
	cobsleep.c \
	kanaconv.c 

CJSRCS = orcsjistoeuc.c

CJQSRCS = orcqrencode.c

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global
