SRCS = ORCGT01.CBL \
       ORCGT02.CBL \
       ORCGT03.CBL \
       ORCGTERR.CBL \
       ORCGTID1.CBL \
       ORCGTID2.CBL \
       ORCGT99.CBL \
       ORCGT91.CBL

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

