SRCS = ORCR0010.CBL \
       ORCR0020.CBL \
       ORCR0030.CBL \
       ORCR0035.CBL \
       ORCR0038.CBL \
       ORCR0040.CBL \
       ORCR0050.CBL \
       ORCR0055.CBL \
       ORCR0090.CBL \
       ORCR0091.CBL \
       ORCR0100.CBL \
       ORCR0101.CBL \
       ORCR0102.CBL \
       ORCR0103.CBL \
       ORCR0104.CBL \
       ORCBPREV1.CBL \
       ORCBPREV.CBL \
       ORCBPRT1.CBL \
       ORCBPRT.CBL \
       ORCR0200.CBL \
       ORCR0210.CBL \
       ORCR0300.CBL \
       ORCRCP060.CBL \
       ORCRCP400.CBL \
       ORCRSYUKA01.CBL \
       ORCBT010.CBL \
       ORCBT020.CBL \
       ORCBT110.CBL \
       ORCBT120.CBL \
       ORCBT130.CBL \


top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

