OBJS = ORCGZ01.so   ORCGZ02.so   ORCGZ03.so   ORCGZ04.so   ORCGZ05.so \
       ORCGZ90.so   ORCGZ98.so   ORCGZ99.so   ORCGZERR.so  ORCGZID1.so \
       ORCGZS01.so  ORCGZ91.so   ORCGZID2.so  ORCGZ97.so   ORCGZ06.so

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global
