OBJS = ORCGK01.so   ORCGK02.so   ORCGK021.so   ORCGK022.so   ORCGK023.so \
       ORCGK03.so   ORCGK04.so   ORCGK05.so    ORCGK051.so   ORCGK06.so \
       ORCGK07.so   ORCGK08.so   ORCGK09.so    ORCGK98.so    ORCGK99.so \
       ORCGKERR.so  ORCGKID1.so  ORCGK10.so    ORCSC10S.so \
       ORCSC10S200203.so         ORCSC10S200204.so \
       ORCHCSET.so  ORCGK052.so  ORCGKID2.so

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global
