SRCS = ORCGK01.CBL \
       ORCGK02.CBL \
       ORCGK021.CBL \
       ORCGK022.CBL \
       ORCGK023.CBL \
       ORCGK03.CBL \
       ORCGK04.CBL \
       ORCGK05.CBL \
       ORCGK051.CBL \
       ORCGK06.CBL \
       ORCGK07.CBL \
       ORCGK08.CBL \
       ORCGK09.CBL \
       ORCGK98.CBL \
       ORCGK99.CBL \
       ORCGKERR.CBL \
       ORCGKID1.CBL \
       ORCGK10.CBL \
       ORCSC10S.CBL \
       ORCSC10S200203.CBL \
       ORCSC10S200204.CBL \
       ORCHCSET.CBL \
       ORCGK052.CBL \
       ORCGKID2.CBL \
       ORCGKERR2.CBL \
       ORCGK02NYU.CBL

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

