SRCS = \
	ORCGI41.CBL \
	ORCGI4ERR.CBL \
	ORCGI4ID1.CBL \
	ORCGI42.CBL \
	ORCGI43.CBL \
	ORCGI44.CBL \
	ORCGI45.CBL \
	ORCGI46.CBL \
	ORCGI47.CBL \
	ORCGI48.CBL \
	ORCGI49.CBL


top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

