SRCS = ORCGI20.CBL \
       ORCGI21.CBL \
       ORCGI22.CBL \
       ORCGI23.CBL \
       ORCGI2ERR.CBL \
       ORCGI2ID1.CBL \
       ORCGI2SUB01.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

