#!/usr/bin/ruby

class Receden_common_const

  H200401 = "20080401"
  H210101 = "20090101"
  H210501 = "20090501"
  H210801 = "20090801"
  H230401 = "20110401"
  H240301 = "20120301"
  H240401 = "20120401"
  H270101 = "20150101"

  N = NUMERIC      = 0
  A = ALPHANUMERIC = 1
  K = KANJI        = 2
  T = TEXT         = 3 #(A or K)

  #-------------------------------------------------------------------------------
  #   Record Definition
  #-------------------------------------------------------------------------------
  IRrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"         ,"RECID"   ,A, 2 ,true  ,true],
  ["¿³ºº»ÙÊ§µ¡´Ø"             ,"SSKKN"   ,N, 1 ,true  ,true],
  ["ÅÔÆ»ÉÜ¸©"                 ,"PREFNUM" ,N, 2 ,true  ,true],
  ["ÅÀ¿ôÉ½"                   ,"TNSNUM"  ,N, 1 ,true  ,true],
  ["°åÎÅµ¡´Ø¥³¡¼¥É"           ,"HOSPCD"  ,N, 7 ,true  ,true],
  ["Í½È÷"                     ,"YOBI"    ,N, 2 ,false ,false],
  ["°åÎÅµ¡´ØÌ¾¾Î"             ,"HOSPNAME",K,40 ,false ,true],
  ["ÀÁµáÇ¯·î"                 ,"SKYYM"   ,N, 5 ,true  ,true],
  ["¥Ş¥ë¥Á¥Ü¥ê¥å¡¼¥à¼±ÊÌ¾ğÊó" ,"MVOLID"  ,N, 2 ,true  ,true],
  ["ÅÅÏÃÈÖ¹æ"                 ,"TEL"     ,A,15 ,false ,false]

  RErecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"         ,"RECID"            ,A, 2 ,true ,true],
  ["¥ì¥»¥×¥ÈÈÖ¹æ"             ,"RECENUM"          ,N, 6 ,false,true],
  ["¥ì¥»¥×¥È¼ïÊÌ"             ,"RECESBT"          ,N, 4 ,true ,true],
  ["¿ÇÎÅÇ¯·î"                 ,"SRYYM"            ,N, 5 ,true ,true],
  ["»áÌ¾"                     ,"NAME"             ,T,40 ,false,true],
  ["ÃË½÷¶èÊ¬"                 ,"SEX"              ,N, 1 ,true ,true],
  ["À¸Ç¯·îÆü"                 ,"BIRTHDAY"         ,N, 7 ,true ,true],
  ["µëÉÕ³ä¹ç"                 ,"KFRATE"           ,N, 3 ,false,false],
  ["Æş±¡Ç¯·îÆü"               ,"NYUINYMD"         ,N, 7 ,false,false],
  ["ÉÂÅï¶èÊ¬"                 ,"BTUKBN"           ,A, 8 ,false,false],
  ["°ìÉôÉéÃ´¶â¡¦¿©»öÎÅÍÜÈñ¡¦À¸³èÎÅÍÜÈñÉ¸½àÉéÃ´³Û¶èÊ¬","SKJFTNKBN",N,1,false,false],
  ["¥ì¥»¥×¥ÈÆÃµ­»ö¹à"         ,"TOKKI"            ,A,10 ,false,false],
  ["ÉÂ¾²¿ô"                   ,"BEDSU"            ,N, 4 ,false,false],
  ["¥«¥ë¥ÆÈÖ¹æÅù"             ,"PTNUM"            ,A,20 ,false,false],
  ["³ä°úÅÀ¿ôÃ±²Á"             ,"DCTEN"            ,N, 2 ,false,false],
  ["Í½È÷"                     ,"YOBI1"            ,N, 1 ,false,false],
  ["Í½È÷"                     ,"YOBI2"            ,N, 1 ,false,false],
  ["µì¿ÇÎÅ²Ê"                 ,"OLDSRYKA"         ,N, 2 ,false,false],
  ["¸¡º÷ÈÖ¹æ"                 ,"SELNUM"           ,N,30 ,false,false],
  ["µ­Ï¿¾ò·ï»ÅÍÍÇ¯·î¾ğÊó"     ,"RECYM"            ,N, 5 ,false,false],
  ["ÀÁµá¾ğÊó"                 ,"SKYINF"           ,A,40 ,false,false],
  ["¿ÇÎÅ²Ê£±¿ÇÎÅ²ÊÌ¾"         ,"SRYKA1_CD"                 ,N,2,false,false],
  ["¿ÇÎÅ²Ê£±ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î¿ÍÂÎ¤ÎÉô°ÌÅù","SRYKA1_BUI"       ,N,3,false,false],
  ["¿ÇÎÅ²Ê£±ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÀ­ÊÌÅù"      ,"SRYKA1_SEX"       ,N,3,false,false],
  ["¿ÇÎÅ²Ê£±ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î°å³ØÅª½èÃÖ"  ,"SRYKA1_SHOCHI"    ,N,3,false,false],
  ["¿ÇÎÅ²Ê£±ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÆÃÄê¼ÀÉÂ"    ,"SRYKA1_TOKSIPPEI" ,N,3,false,false],
  ["¿ÇÎÅ²Ê£²¿ÇÎÅ²ÊÌ¾"                  ,"SRYKA2_CD"        ,N,2,false,false],
  ["¿ÇÎÅ²Ê£²ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î¿ÍÂÎ¤ÎÉô°ÌÅù","SRYKA2_BUI"       ,N,3,false,false],
  ["¿ÇÎÅ²Ê£²ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÀ­ÊÌÅù"      ,"SRYKA2_SEX"       ,N,3,false,false],
  ["¿ÇÎÅ²Ê£²ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î°å³ØÅª½èÃÖ"  ,"SRYKA2_SHOCHI"    ,N,3,false,false],
  ["¿ÇÎÅ²Ê£²ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÆÃÄê¼ÀÉÂ"    ,"SRYKA2_TOKSIPPEI" ,N,3,false,false],
  ["¿ÇÎÅ²Ê£³¿ÇÎÅ²ÊÌ¾"                  ,"SRYKA3_CD"        ,N,2,false,false],
  ["¿ÇÎÅ²Ê£³ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î¿ÍÂÎ¤ÎÉô°ÌÅù","SRYKA3_BUI"       ,N,3,false,false],
  ["¿ÇÎÅ²Ê£³ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÀ­ÊÌÅù"      ,"SRYKA3_SEX"       ,N,3,false,false],
  ["¿ÇÎÅ²Ê£³ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î°å³ØÅª½èÃÖ"  ,"SRYKA3_SHOCHI"    ,N,3,false,false],
  ["¿ÇÎÅ²Ê£³ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÆÃÄê¼ÀÉÂ"    ,"SRYKA3_TOKSIPPEI" ,N,3,false,false]

  HOrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A, 2,true ,true],
  ["Êİ¸±¼ÔÈÖ¹æ"                  ,"HKNJANUM"         ,A, 8,true ,true],
  ["ÈïÊİ¸±¼Ô¾Ú¡Ê¼êÄ¢¡ËÅù¤Îµ­¹æ"  ,"KIGO"             ,T,40,false,false],
  ["ÈïÊİ¸±¼Ô¾Ú¡Ê¼êÄ¢¡ËÅù¤ÎÈÖ¹æ"  ,"NUM"              ,T,40,false,true],
  ["¿ÇÎÅ¼ÂÆü¿ô"                  ,"JNISSU"           ,N, 2,false,true],
  ["¹ç·×ÅÀ¿ô"                    ,"TEN"              ,N, 8,false,true],
  ["Í½È÷"                        ,"YOBI"             ,N, 5,false,false],
  ["¿©»öÎÅÍÜ¡¦À¸³èÎÅÍÜ²ó¿ô"      ,"SSKAISU"          ,N, 2,false,false],
  ["¿©»öÎÅÍÜ¡¦À¸³èÎÅÍÜ¹ç·×¶â³Û"  ,"SSMONEY"          ,N, 8,false,false],
  ["¿¦Ì³¾å¤Î»öÍ³"                ,"RIYU"             ,N, 1,false,false],
  ["¾ÚÌÀ½ñÈÖ¹æ"                  ,"CERTNUM"          ,N, 3,false,false],
  ["ÉéÃ´¶â³Û°åÎÅÊİ¸±"            ,"FTN"              ,N, 9,false,false],
  ["ÉéÃ´¶â³Û¸ºÌÈ¶èÊ¬"            ,"DCKBN"            ,N, 1,false,false],
  ["ÉéÃ´¶â³Û¸º³Û³ä¹ç"            ,"DCRATE"           ,N, 3,false,false],
  ["ÉéÃ´¶â³Û¸º³Û¶â³Û"            ,"DCMONEY"          ,N, 6,false,false]



  ROrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A, 2,true ,true],
  ["Êİ¸±¼ÔÈÖ¹æ"                  ,"HKNJANUM"         ,A, 8,true ,true],
  ["ÈïÊİ¸±¼Ô¾Ú¡Ê¼êÄ¢¡ËÅù¤Îµ­¹æ"  ,"KIGO"             ,T,40,false,false],
  ["ÈïÊİ¸±¼Ô¾Ú¡Ê¼êÄ¢¡ËÅù¤ÎÈÖ¹æ"  ,"NUM"              ,T,40,false,true],
  ["¿ÇÎÅ¼ÂÆü¿ô"                  ,"JNISSU"           ,N, 2,false,true],
  ["¹ç·×ÅÀ¿ô"                    ,"TEN"              ,N, 8,false,true],
  ["Í½È÷"                        ,"YOBI"             ,N, 5,false,false],
  ["¿©»öÎÅÍÜ¡¦À¸³èÎÅÍÜ²ó¿ô"      ,"SSKAISU"         ,N, 2,false,false],
  ["¿©»öÎÅÍÜ¡¦À¸³èÎÅÍÜ¹ç·×¶â³Û"  ,"SSMONEY"         ,N, 8,false,false],
  ["Ï·¿Í°åÎÅ»ÔÄ®Â¼ÈÖ¹æ"          ,"FTNNUM"           ,A, 8,true ,true],
  ["Ï·¿Í°åÎÅ¼õµë¼ÔÈÖ¹æ"          ,"JKYNUM"           ,A, 7,true ,true],
  ["ÉéÃ´¶â³ÛÏ·¿Í¸ºÌÈ¶èÊ¬"        ,"DCKBN"            ,N, 1,false,false],
  ["ÉéÃ´¶â³ÛÏ·¿Í³°Íè¶â³Û"        ,"GAIFTN"           ,N, 6,false,false],
  ["ÉéÃ´¶â³ÛÏ·¿ÍÆş±¡¶â³Û"        ,"NYUFTN"           ,N, 6,false,false]

  KOrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A,2, true,true ],
  ["¸øÈñÉéÃ´°åÎÅÉéÃ´¼ÔÈÖ¹æ"      ,"FTNNUM"           ,A,8, true,true ],
  ["¸øÈñÉéÃ´°åÎÅ¼õµë¼ÔÈÖ¹æ"      ,"JKYNUM"           ,N,7,false,false],
  ["¸øÈñÉéÃ´°åÎÅÇ¤°ÕµëÉÕ¶èÊ¬"    ,"NINKEIKBN"        ,N,1,false,false],
  ["¿ÇÎÅ¼ÂÆü¿ô"                  ,"JNISSU"           ,N,2,false,true ],
  ["¹ç·×ÅÀ¿ô"                    ,"TEN"              ,N,8,false,true ],
  ["ÉéÃ´¶â³Û¸øÈñ"                ,"KMONEY"           ,N,8,false,false],
  ["ÉéÃ´¶â³Û³°Íè°ìÉôÉéÃ´¶â¸øÈñµëÉÕÂĞ¾İ","GAIFTN"     ,N,6,false,false],
  ["ÉéÃ´¶â³ÛÆş±¡°ìÉôÉéÃ´¶â¸øÈñµëÉÕÂĞ¾İ","NYUFTN"     ,N,6,false,false],
  ["Í½È÷"                        ,"YOBI"             ,N,5,false,false],
  ["¿©»öÎÅÍÜ¡¦À¸³èÎÅÍÜ²ó¿ô"      ,"SSKAISU"          ,N,2,false,false],
  ["¿©»öÎÅÍÜ¡¦À¸³èÎÅÍÜ¹ç·×¶â³Û"  ,"SSMONEY"          ,N,8,false,false]

  KHrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A,  2,true ,true],
  ["¹ñÊİÏ¢¸ÇÍ­¾ğÊó"              ,"TEXT"             ,T,100,false,false]

  SYrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A,  2,true ,true ],
  ["½ıÉÂÌ¾¥³¡¼¥É"                ,"BYOMEICD"         ,N,  7,true ,true ],
  ["¿ÇÎÅ³«»ÏÆü"                  ,"SRYYMD"           ,N,  7,true ,true ],
  ["Å¾µ¢¶èÊ¬"                    ,"TENKIKBN"         ,N,  1,true ,true ],
  ["½¤¾ş¸ì¥³¡¼¥É"                ,"MODCD"            ,A, 80,false,false],
  ["½ıÉÂÌ¾¾Î"                    ,"BYOMEI"           ,K, 40,false,false],
  ["¼ç½ıÉÂ"                      ,"SYUBYO"           ,N,  2,false,false],
  ["ÊäÂ­¥³¥á¥ó¥È"                ,"HSKCOM"           ,K, 40,false,false]

  SIrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A,   2,true ,true ],
  ["¿ÇÎÅ¼±ÊÌ"                    ,"SRYKBN"           ,N,   2,false,false],
  ["ÉéÃ´¶èÊ¬"                    ,"FTNKBN"           ,A,   1,true ,true ],
  ["¿ÇÎÅ¹Ô°Ù¥³¡¼¥É"              ,"SRYCD"            ,N,   9,true ,true ],
  ["¿ôÎÌ¥Ç¡¼¥¿"                  ,"SURYO"            ,N,   8,false,false],
  ["ÅÀ¿ô"                        ,"TEN"              ,N,   7,false,false],
  ["²ó¿ô"                        ,"KAISU"            ,N,   3,false,false],
  ["¥³¥á¥ó¥È¥³¡¼¥É£±"            ,"COMCD1"           ,N,   9,false,false],
  ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£±"        ,"COMMENT1"         ,K, 100,false,false],
  ["¥³¥á¥ó¥È¥³¡¼¥É£²"            ,"COMCD2"           ,N,   9,false,false],
  ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£²"        ,"COMMENT2"         ,K, 100,false,false],
  ["¥³¥á¥ó¥È¥³¡¼¥É£³"            ,"COMCD3"           ,N,   9,false,false],
  ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£³"        ,"COMMENT3"         ,K, 100,false,false],
  ["£±Æü¤Î¾ğÊó"                  ,"DAY01"            ,N,   3,false,false],
  ["£²Æü¤Î¾ğÊó"                  ,"DAY02"            ,N,   3,false,false],
  ["£³Æü¤Î¾ğÊó"                  ,"DAY03"            ,N,   3,false,false],
  ["£´Æü¤Î¾ğÊó"                  ,"DAY04"            ,N,   3,false,false],
  ["£µÆü¤Î¾ğÊó"                  ,"DAY05"            ,N,   3,false,false],
  ["£¶Æü¤Î¾ğÊó"                  ,"DAY06"            ,N,   3,false,false],
  ["£·Æü¤Î¾ğÊó"                  ,"DAY07"            ,N,   3,false,false],
  ["£¸Æü¤Î¾ğÊó"                  ,"DAY08"            ,N,   3,false,false],
  ["£¹Æü¤Î¾ğÊó"                  ,"DAY09"            ,N,   3,false,false],
  ["£±£°Æü¤Î¾ğÊó"                ,"DAY10"            ,N,   3,false,false],
  ["£±£±Æü¤Î¾ğÊó"                ,"DAY11"            ,N,   3,false,false],
  ["£±£²Æü¤Î¾ğÊó"                ,"DAY12"            ,N,   3,false,false],
  ["£±£³Æü¤Î¾ğÊó"                ,"DAY13"            ,N,   3,false,false],
  ["£±£´Æü¤Î¾ğÊó"                ,"DAY14"            ,N,   3,false,false],
  ["£±£µÆü¤Î¾ğÊó"                ,"DAY15"            ,N,   3,false,false],
  ["£±£¶Æü¤Î¾ğÊó"                ,"DAY16"            ,N,   3,false,false],
  ["£±£·Æü¤Î¾ğÊó"                ,"DAY17"            ,N,   3,false,false],
  ["£±£¸Æü¤Î¾ğÊó"                ,"DAY18"            ,N,   3,false,false],
  ["£±£¹Æü¤Î¾ğÊó"                ,"DAY19"            ,N,   3,false,false],
  ["£²£°Æü¤Î¾ğÊó"                ,"DAY20"            ,N,   3,false,false],
  ["£²£±Æü¤Î¾ğÊó"                ,"DAY21"            ,N,   3,false,false],
  ["£²£²Æü¤Î¾ğÊó"                ,"DAY22"            ,N,   3,false,false],
  ["£²£³Æü¤Î¾ğÊó"                ,"DAY23"            ,N,   3,false,false],
  ["£²£´Æü¤Î¾ğÊó"                ,"DAY24"            ,N,   3,false,false],
  ["£²£µÆü¤Î¾ğÊó"                ,"DAY25"            ,N,   3,false,false],
  ["£²£¶Æü¤Î¾ğÊó"                ,"DAY26"            ,N,   3,false,false],
  ["£²£·Æü¤Î¾ğÊó"                ,"DAY27"            ,N,   3,false,false],
  ["£²£¸Æü¤Î¾ğÊó"                ,"DAY28"            ,N,   3,false,false],
  ["£²£¹Æü¤Î¾ğÊó"                ,"DAY29"            ,N,   3,false,false],
  ["£³£°Æü¤Î¾ğÊó"                ,"DAY30"            ,N,   3,false,false],
  ["£³£±Æü¤Î¾ğÊó"                ,"DAY31"            ,N,   3,false,false]


  IYrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A,  2,true ,true],
  ["¿ÇÎÅ¼±ÊÌ"                    ,"SRYKBN"           ,N,  2,false,false],
  ["ÉéÃ´¶èÊ¬"                    ,"FTNKBN"           ,A,  1,true ,true],
  ["°åÌôÉÊ¥³¡¼¥É"                ,"SRYCD"            ,N,  9,true ,true],
  ["»ÈÍÑÎÌ"                      ,"SURYO"            ,A, 11,false,false],
  ["ÅÀ¿ô"                        ,"TEN"              ,N,  7,false,false],
  ["²ó¿ô"                        ,"KAISU"            ,N,  3,false,false],
  ["¥³¥á¥ó¥È¥³¡¼¥É£±"            ,"COMCD1"           ,N,  9,false,false],
  ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£±"        ,"COMMENT1"         ,K,100,false,false],
  ["¥³¥á¥ó¥È¥³¡¼¥É£²"            ,"COMCD2"           ,N,  9,false,false],
  ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£²"        ,"COMMENT2"         ,K,100,false,false],
  ["¥³¥á¥ó¥È¥³¡¼¥É£³"            ,"COMCD3"           ,N,  9,false,false],
  ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£³"        ,"COMMENT3"         ,K,100,false,false],
  ["£±Æü¤Î¾ğÊó"                  ,"DAY01"            ,N,  3,false,false],
  ["£²Æü¤Î¾ğÊó"                  ,"DAY02"            ,N,  3,false,false],
  ["£³Æü¤Î¾ğÊó"                  ,"DAY03"            ,N,  3,false,false],
  ["£´Æü¤Î¾ğÊó"                  ,"DAY04"            ,N,  3,false,false],
  ["£µÆü¤Î¾ğÊó"                  ,"DAY05"            ,N,  3,false,false],
  ["£¶Æü¤Î¾ğÊó"                  ,"DAY06"            ,N,  3,false,false],
  ["£·Æü¤Î¾ğÊó"                  ,"DAY07"            ,N,  3,false,false],
  ["£¸Æü¤Î¾ğÊó"                  ,"DAY08"            ,N,  3,false,false],
  ["£¹Æü¤Î¾ğÊó"                  ,"DAY09"            ,N,  3,false,false],
  ["£±£°Æü¤Î¾ğÊó"                ,"DAY10"            ,N,  3,false,false],
  ["£±£±Æü¤Î¾ğÊó"                ,"DAY11"            ,N,  3,false,false],
  ["£±£²Æü¤Î¾ğÊó"                ,"DAY12"            ,N,  3,false,false],
  ["£±£³Æü¤Î¾ğÊó"                ,"DAY13"            ,N,  3,false,false],
  ["£±£´Æü¤Î¾ğÊó"                ,"DAY14"            ,N,  3,false,false],
  ["£±£µÆü¤Î¾ğÊó"                ,"DAY15"            ,N,  3,false,false],
  ["£±£¶Æü¤Î¾ğÊó"                ,"DAY16"            ,N,  3,false,false],
  ["£±£·Æü¤Î¾ğÊó"                ,"DAY17"            ,N,  3,false,false],
  ["£±£¸Æü¤Î¾ğÊó"                ,"DAY18"            ,N,  3,false,false],
  ["£±£¹Æü¤Î¾ğÊó"                ,"DAY19"            ,N,  3,false,false],
  ["£²£°Æü¤Î¾ğÊó"                ,"DAY20"            ,N,  3,false,false],
  ["£²£±Æü¤Î¾ğÊó"                ,"DAY21"            ,N,  3,false,false],
  ["£²£²Æü¤Î¾ğÊó"                ,"DAY22"            ,N,  3,false,false],
  ["£²£³Æü¤Î¾ğÊó"                ,"DAY23"            ,N,  3,false,false],
  ["£²£´Æü¤Î¾ğÊó"                ,"DAY24"            ,N,  3,false,false],
  ["£²£µÆü¤Î¾ğÊó"                ,"DAY25"            ,N,  3,false,false],
  ["£²£¶Æü¤Î¾ğÊó"                ,"DAY26"            ,N,  3,false,false],
  ["£²£·Æü¤Î¾ğÊó"                ,"DAY27"            ,N,  3,false,false],
  ["£²£¸Æü¤Î¾ğÊó"                ,"DAY28"            ,N,  3,false,false],
  ["£²£¹Æü¤Î¾ğÊó"                ,"DAY29"            ,N,  3,false,false],
  ["£³£°Æü¤Î¾ğÊó"                ,"DAY30"            ,N,  3,false,false],
  ["£³£±Æü¤Î¾ğÊó"                ,"DAY31"            ,N,  3,false,false]

  TOrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A,  2,true ,true ],
  ["¿ÇÎÅ¼±ÊÌ"                    ,"SRYKBN"           ,N,  2,false,false],
  ["ÉéÃ´¶èÊ¬"                    ,"FTNKBN"           ,A,  1,true ,true ],
  ["ÆÃÄê´ïºà¥³¡¼¥É"              ,"SRYCD"            ,N,  9,true ,true ],
  ["»ÈÍÑÎÌ"                      ,"SURYO"            ,A,  9,false,false],
  ["ÅÀ¿ô"                        ,"TEN"              ,N,  7,false,false],
  ["²ó¿ô"                        ,"KAISU"            ,N,  3,false,false],
  ["Ã±°Ì¥³¡¼¥É"                  ,"TANICD"           ,N,  3,false,false],
  ["Ã±²Á"                        ,"TANKA"            ,A, 11,false,false],
  ["ÆÃÄê´ïºàÌ¾¾Î"                ,"NAME"             ,K, 40,false,false],
  ["¾¦ÉÊÌ¾µÚ¤Óµ¬³ÊËô¤Ï¥µ¥¤¥º"    ,"INFO"             ,K,300,false,false],
  ["¥³¥á¥ó¥È¥³¡¼¥É£±"            ,"COMCD1"           ,N,  9,false,false],
  ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£±"        ,"COMMENT1"         ,K,100,false,false],
  ["¥³¥á¥ó¥È¥³¡¼¥É£²"            ,"COMCD2"           ,N,  9,false,false],
  ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£²"        ,"COMMENT2"         ,K,100,false,false],
  ["¥³¥á¥ó¥È¥³¡¼¥É£³"            ,"COMCD3"           ,N,  9,false,false],
  ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£³"        ,"COMMENT3"         ,K,100,false,false],
  ["£±Æü¤Î¾ğÊó"                  ,"DAY01"            ,N,  3,false,false],
  ["£²Æü¤Î¾ğÊó"                  ,"DAY02"            ,N,  3,false,false],
  ["£³Æü¤Î¾ğÊó"                  ,"DAY03"            ,N,  3,false,false],
  ["£´Æü¤Î¾ğÊó"                  ,"DAY04"            ,N,  3,false,false],
  ["£µÆü¤Î¾ğÊó"                  ,"DAY05"            ,N,  3,false,false],
  ["£¶Æü¤Î¾ğÊó"                  ,"DAY06"            ,N,  3,false,false],
  ["£·Æü¤Î¾ğÊó"                  ,"DAY07"            ,N,  3,false,false],
  ["£¸Æü¤Î¾ğÊó"                  ,"DAY08"            ,N,  3,false,false],
  ["£¹Æü¤Î¾ğÊó"                  ,"DAY09"            ,N,  3,false,false],
  ["£±£°Æü¤Î¾ğÊó"                ,"DAY10"            ,N,  3,false,false],
  ["£±£±Æü¤Î¾ğÊó"                ,"DAY11"            ,N,  3,false,false],
  ["£±£²Æü¤Î¾ğÊó"                ,"DAY12"            ,N,  3,false,false],
  ["£±£³Æü¤Î¾ğÊó"                ,"DAY13"            ,N,  3,false,false],
  ["£±£´Æü¤Î¾ğÊó"                ,"DAY14"            ,N,  3,false,false],
  ["£±£µÆü¤Î¾ğÊó"                ,"DAY15"            ,N,  3,false,false],
  ["£±£¶Æü¤Î¾ğÊó"                ,"DAY16"            ,N,  3,false,false],
  ["£±£·Æü¤Î¾ğÊó"                ,"DAY17"            ,N,  3,false,false],
  ["£±£¸Æü¤Î¾ğÊó"                ,"DAY18"            ,N,  3,false,false],
  ["£±£¹Æü¤Î¾ğÊó"                ,"DAY19"            ,N,  3,false,false],
  ["£²£°Æü¤Î¾ğÊó"                ,"DAY20"            ,N,  3,false,false],
  ["£²£±Æü¤Î¾ğÊó"                ,"DAY21"            ,N,  3,false,false],
  ["£²£²Æü¤Î¾ğÊó"                ,"DAY22"            ,N,  3,false,false],
  ["£²£³Æü¤Î¾ğÊó"                ,"DAY23"            ,N,  3,false,false],
  ["£²£´Æü¤Î¾ğÊó"                ,"DAY24"            ,N,  3,false,false],
  ["£²£µÆü¤Î¾ğÊó"                ,"DAY25"            ,N,  3,false,false],
  ["£²£¶Æü¤Î¾ğÊó"                ,"DAY26"            ,N,  3,false,false],
  ["£²£·Æü¤Î¾ğÊó"                ,"DAY27"            ,N,  3,false,false],
  ["£²£¸Æü¤Î¾ğÊó"                ,"DAY28"            ,N,  3,false,false],
  ["£²£¹Æü¤Î¾ğÊó"                ,"DAY29"            ,N,  3,false,false],
  ["£³£°Æü¤Î¾ğÊó"                ,"DAY30"            ,N,  3,false,false],
  ["£³£±Æü¤Î¾ğÊó"                ,"DAY31"            ,N,  3,false,false]

  COrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A,  2,true ,true  ],
  ["¿ÇÎÅ¼±ÊÌ"                    ,"SRYKBN"           ,N,  2,false,false ],
  ["ÉéÃ´¶èÊ¬"                    ,"FTNKBN"           ,A,  1,true ,true  ],
  ["¥³¥á¥ó¥È¥³¡¼¥É"              ,"SRYCD"            ,N,  9,true ,true  ],
  ["Ê¸»ú¥Ç¡¼¥¿"                  ,"DATA"             ,K, 76,false,false ]

  NIrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A,2,true ,true ],
  ["£±Æü¤Î¾ğÊó"                  ,"DAY01"            ,N,3,false,false],
  ["£²Æü¤Î¾ğÊó"                  ,"DAY02"            ,N,3,false,false],
  ["£³Æü¤Î¾ğÊó"                  ,"DAY03"            ,N,3,false,false],
  ["£´Æü¤Î¾ğÊó"                  ,"DAY04"            ,N,3,false,false],
  ["£µÆü¤Î¾ğÊó"                  ,"DAY05"            ,N,3,false,false],
  ["£¶Æü¤Î¾ğÊó"                  ,"DAY06"            ,N,3,false,false],
  ["£·Æü¤Î¾ğÊó"                  ,"DAY07"            ,N,3,false,false],
  ["£¸Æü¤Î¾ğÊó"                  ,"DAY08"            ,N,3,false,false],
  ["£¹Æü¤Î¾ğÊó"                  ,"DAY09"            ,N,3,false,false],
  ["£±£°Æü¤Î¾ğÊó"                ,"DAY10"            ,N,3,false,false],
  ["£±£±Æü¤Î¾ğÊó"                ,"DAY11"            ,N,3,false,false],
  ["£±£²Æü¤Î¾ğÊó"                ,"DAY12"            ,N,3,false,false],
  ["£±£³Æü¤Î¾ğÊó"                ,"DAY13"            ,N,3,false,false],
  ["£±£´Æü¤Î¾ğÊó"                ,"DAY14"            ,N,3,false,false],
  ["£±£µÆü¤Î¾ğÊó"                ,"DAY15"            ,N,3,false,false],
  ["£±£¶Æü¤Î¾ğÊó"                ,"DAY16"            ,N,3,false,false],
  ["£±£·Æü¤Î¾ğÊó"                ,"DAY17"            ,N,3,false,false],
  ["£±£¸Æü¤Î¾ğÊó"                ,"DAY18"            ,N,3,false,false],
  ["£±£¹Æü¤Î¾ğÊó"                ,"DAY19"            ,N,3,false,false],
  ["£²£°Æü¤Î¾ğÊó"                ,"DAY20"            ,N,3,false,false],
  ["£²£±Æü¤Î¾ğÊó"                ,"DAY21"            ,N,3,false,false],
  ["£²£²Æü¤Î¾ğÊó"                ,"DAY22"            ,N,3,false,false],
  ["£²£³Æü¤Î¾ğÊó"                ,"DAY23"            ,N,3,false,false],
  ["£²£´Æü¤Î¾ğÊó"                ,"DAY24"            ,N,3,false,false],
  ["£²£µÆü¤Î¾ğÊó"                ,"DAY25"            ,N,3,false,false],
  ["£²£¶Æü¤Î¾ğÊó"                ,"DAY26"            ,N,3,false,false],
  ["£²£·Æü¤Î¾ğÊó"                ,"DAY27"            ,N,3,false,false],
  ["£²£¸Æü¤Î¾ğÊó"                ,"DAY28"            ,N,3,false,false],
  ["£²£¹Æü¤Î¾ğÊó"                ,"DAY29"            ,N,3,false,false],
  ["£³£°Æü¤Î¾ğÊó"                ,"DAY30"            ,N,3,false,false],
  ["£³£±Æü¤Î¾ğÊó"                ,"DAY31"            ,N,3,false,false]

  SJrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A,   2,true ,true ],
  ["¾É¾õ¾Üµ­¶èÊ¬"                ,"SJKBN"            ,N,   2,false,false],
  ["¾É¾õ¾Üµ­¥Ç¡¼¥¿"              ,"DATA"             ,K,2400,false,false]

  GOrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"            ,"RECID"            ,A, 2,true ,true ],
  ["Áí·ï¿ô"                      ,"TOTALKENSU"       ,N, 6,false,false],
  ["Áí¹ç·×ÅÀ¿ô"                  ,"TOTALTEN"         ,N,10,false,false],
  ["¥Ş¥ë¥Á¥Ü¥ê¥å¡¼¥à¼±ÊÌ¾ğÊó"    ,"MVOLID"           ,N, 2,true ,true ]


  SAIrecord=["¥Ç¡¼¥¿¼±ÊÌ¥³¡¼¥É"           ,"RECID"       ,N,2 ,false ,true ],
  ["¹ÔÈÖ¹æ"                     ,"LINE"        ,N,5 ,false ,true ],
  ["»ŞÈÖ¹æ"                     ,"BRANCH"      ,N,3 ,false ,true ],
  ["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"           ,"DATA01"      ,A,2 ,true  ,true ],
  ["¹àÌÜ£°£²"                   ,"DATA02"      ,T,500,false,false],
  ["¹àÌÜ£°£³"                   ,"DATA03"      ,T,500,false,false],
  ["¹àÌÜ£°£´"                   ,"DATA04"      ,T,500,false,false],
  ["¹àÌÜ£°£µ"                   ,"DATA05"      ,T,500,false,false],
  ["¹àÌÜ£°£¶"                   ,"DATA06"      ,T,500,false,false],
  ["¹àÌÜ£°£·"                   ,"DATA07"      ,T,500,false,false],
  ["¹àÌÜ£°£¸"                   ,"DATA08"      ,T,500,false,false],
  ["¹àÌÜ£°£¹"                   ,"DATA09"      ,T,500,false,false],
  ["¹àÌÜ£±£°"                   ,"DATA10"      ,T,500,false,false],
  ["¹àÌÜ£±£±"                   ,"DATA11"      ,T,500,false,false],
  ["¹àÌÜ£±£²"                   ,"DATA12"      ,T,500,false,false],
  ["¹àÌÜ£±£³"                   ,"DATA13"      ,T,500,false,false],
  ["¹àÌÜ£±£´"                   ,"DATA14"      ,T,500,false,false],
  ["¹àÌÜ£±£µ"                   ,"DATA15"      ,T,500,false,false],
  ["¹àÌÜ£±£¶"                   ,"DATA16"      ,T,500,false,false],
  ["¹àÌÜ£±£·"                   ,"DATA17"      ,T,500,false,false],
  ["¹àÌÜ£±£¸"                   ,"DATA18"      ,T,500,false,false],
  ["¹àÌÜ£±£¹"                   ,"DATA19"      ,T,500,false,false],
  ["¹àÌÜ£²£°"                   ,"DATA20"      ,T,500,false,false],
  ["¹àÌÜ£²£±"                   ,"DATA21"      ,T,500,false,false],
  ["¹àÌÜ£²£²"                   ,"DATA22"      ,T,500,false,false],
  ["¹àÌÜ£²£³"                   ,"DATA23"      ,T,500,false,false],
  ["¹àÌÜ£²£´"                   ,"DATA24"      ,T,500,false,false],
  ["¹àÌÜ£²£µ"                   ,"DATA25"      ,T,500,false,false],
  ["¹àÌÜ£²£¶"                   ,"DATA26"      ,T,500,false,false],
  ["¹àÌÜ£²£·"                   ,"DATA27"      ,T,500,false,false],
  ["¹àÌÜ£²£¸"                   ,"DATA28"      ,T,500,false,false],
  ["¹àÌÜ£²£¹"                   ,"DATA29"      ,T,500,false,false],
  ["¹àÌÜ£³£°"                   ,"DATA30"      ,T,500,false,false],
  ["¹àÌÜ£³£±"                   ,"DATA31"      ,T,500,false,false],
  ["¹àÌÜ£³£²"                   ,"DATA32"      ,T,500,false,false],
  ["¹àÌÜ£³£³"                   ,"DATA33"      ,T,500,false,false],
  ["¹àÌÜ£³£´"                   ,"DATA34"      ,T,500,false,false],
  ["¹àÌÜ£³£µ"                   ,"DATA35"      ,T,500,false,false],
  ["¹àÌÜ£³£¶"                   ,"DATA36"      ,T,500,false,false],
  ["¹àÌÜ£³£·"                   ,"DATA37"      ,T,500,false,false],
  ["¹àÌÜ£³£¸"                   ,"DATA38"      ,T,500,false,false],
  ["¹àÌÜ£³£¹"                   ,"DATA39"      ,T,500,false,false],
  ["¹àÌÜ£´£°"                   ,"DATA40"      ,T,500,false,false],
  ["¹àÌÜ£´£±"                   ,"DATA41"      ,T,500,false,false],
  ["¹àÌÜ£´£²"                   ,"DATA42"      ,T,500,false,false],
  ["¹àÌÜ£´£³"                   ,"DATA43"      ,T,500,false,false],
  ["¹àÌÜ£´£´"                   ,"DATA44"      ,T,500,false,false],
  ["¹àÌÜ£´£µ"                   ,"DATA45"      ,T,500,false,false],
  ["¹àÌÜ£´£¶"                   ,"DATA46"      ,T,500,false,false],
  ["¹àÌÜ£´£·"                   ,"DATA47"      ,T,500,false,false],
  ["¹àÌÜ£´£¸"                   ,"DATA48"      ,T,500,false,false],
  ["¹àÌÜ£´£¹"                   ,"DATA49"      ,T,500,false,false],
  ["¹àÌÜ£µ£°"                   ,"DATA50"      ,T,500,false,false],
  ["¹àÌÜ£µ£±"                   ,"DATA51"      ,T,500,false,false],
  ["¹àÌÜ£µ£²"                   ,"DATA52"      ,T,500,false,false],
  ["¹àÌÜ£µ£³"                   ,"DATA53"      ,T,500,false,false],
  ["¹àÌÜ£µ£´"                   ,"DATA54"      ,T,500,false,false],
  ["¹àÌÜ£µ£µ"                   ,"DATA55"      ,T,500,false,false],
  ["¹àÌÜ£µ£¶"                   ,"DATA56"      ,T,500,false,false],
  ["¹àÌÜ£µ£·"                   ,"DATA57"      ,T,500,false,false],
  ["¹àÌÜ£µ£¸"                   ,"DATA58"      ,T,500,false,false],
  ["¹àÌÜ£µ£¹"                   ,"DATA59"      ,T,500,false,false],
  ["¹àÌÜ£¶£°"                   ,"DATA60"      ,T,500,false,false],
  ["¹àÌÜ£¶£±"                   ,"DATA61"      ,T,500,false,false],
  ["¹àÌÜ£¶£²"                   ,"DATA62"      ,T,500,false,false],
  ["¹àÌÜ£¶£³"                   ,"DATA63"      ,T,500,false,false],
  ["¹àÌÜ£¶£´"                   ,"DATA64"      ,T,500,false,false],
  ["¹àÌÜ£¶£µ"                   ,"DATA65"      ,T,500,false,false],
  ["¹àÌÜ£¶£¶"                   ,"DATA66"      ,T,500,false,false],
  ["¹àÌÜ£¶£·"                   ,"DATA67"      ,T,500,false,false],
  ["¹àÌÜ£¶£¸"                   ,"DATA68"      ,T,500,false,false],
  ["¹àÌÜ£¶£¹"                   ,"DATA69"      ,T,500,false,false],
  ["¹àÌÜ£·£°"                   ,"DATA70"      ,T,500,false,false],
  ["¹àÌÜ£·£±"                   ,"DATA71"      ,T,500,false,false],
  ["¹àÌÜ£·£²"                   ,"DATA72"      ,T,500,false,false],
  ["¹àÌÜ£·£³"                   ,"DATA73"      ,T,500,false,false],
  ["¹àÌÜ£·£´"                   ,"DATA74"      ,T,500,false,false],
  ["¹àÌÜ£·£µ"                   ,"DATA75"      ,T,500,false,false],
  ["¹àÌÜ£·£¶"                   ,"DATA76"      ,T,500,false,false],
  ["¹àÌÜ£·£·"                   ,"DATA77"      ,T,500,false,false],
  ["¹àÌÜ£·£¸"                   ,"DATA78"      ,T,500,false,false],
  ["¹àÌÜ£·£¹"                   ,"DATA79"      ,T,500,false,false],
  ["¹àÌÜ£¸£°"                   ,"DATA80"      ,T,500,false,false],
  ["¹àÌÜ£¸£±"                   ,"DATA81"      ,T,500,false,false],
  ["¹àÌÜ£¸£²"                   ,"DATA82"      ,T,500,false,false],
  ["¹àÌÜ£¸£³"                   ,"DATA83"      ,T,500,false,false],
  ["¹àÌÜ£¸£´"                   ,"DATA84"      ,T,500,false,false],
  ["¹àÌÜ£¸£µ"                   ,"DATA85"      ,T,500,false,false],
  ["¹àÌÜ£¸£¶"                   ,"DATA86"      ,T,500,false,false],
  ["¹àÌÜ£¸£·"                   ,"DATA87"      ,T,500,false,false],
  ["¹àÌÜ£¸£¸"                   ,"DATA88"      ,T,500,false,false],
  ["¹àÌÜ£¸£¹"                   ,"DATA89"      ,T,500,false,false],
  ["¹àÌÜ£¹£°"                   ,"DATA90"      ,T,500,false,false],
  ["¹àÌÜ£¹£±"                   ,"DATA91"      ,T,500,false,false],
  ["¹àÌÜ£¹£²"                   ,"DATA92"      ,T,500,false,false],
  ["¹àÌÜ£¹£³"                   ,"DATA93"      ,T,500,false,false],
  ["¹àÌÜ£¹£´"                   ,"DATA94"      ,T,500,false,false],
  ["¹àÌÜ£¹£µ"                   ,"DATA95"      ,T,500,false,false],
  ["¹àÌÜ£¹£¶"                   ,"DATA96"      ,T,500,false,false],
  ["¹àÌÜ£¹£·"                   ,"DATA97"      ,T,500,false,false],
  ["¹àÌÜ£¹£¸"                   ,"DATA98"      ,T,500,false,false],
  ["¹àÌÜ£¹£¹"                   ,"DATA99"      ,T,500,false,false]


  ETCrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ğÊó"           ,"RECID"       ,A,2  ,false,false],
  ["¹àÌÜ£°£±"                   ,"DATA01"      ,T,500,false,false],
  ["¹àÌÜ£°£²"                   ,"DATA02"      ,T,500,false,false],
  ["¹àÌÜ£°£³"                   ,"DATA03"      ,T,500,false,false],
  ["¹àÌÜ£°£´"                   ,"DATA04"      ,T,500,false,false],
  ["¹àÌÜ£°£µ"                   ,"DATA05"      ,T,500,false,false],
  ["¹àÌÜ£°£¶"                   ,"DATA06"      ,T,500,false,false],
  ["¹àÌÜ£°£·"                   ,"DATA07"      ,T,500,false,false],
  ["¹àÌÜ£°£¸"                   ,"DATA08"      ,T,500,false,false],
  ["¹àÌÜ£°£¹"                   ,"DATA09"      ,T,500,false,false],
  ["¹àÌÜ£±£°"                   ,"DATA10"      ,T,500,false,false],
  ["¹àÌÜ£±£±"                   ,"DATA11"      ,T,500,false,false],
  ["¹àÌÜ£±£²"                   ,"DATA12"      ,T,500,false,false],
  ["¹àÌÜ£±£³"                   ,"DATA13"      ,T,500,false,false],
  ["¹àÌÜ£±£´"                   ,"DATA14"      ,T,500,false,false],
  ["¹àÌÜ£±£µ"                   ,"DATA15"      ,T,500,false,false],
  ["¹àÌÜ£±£¶"                   ,"DATA16"      ,T,500,false,false],
  ["¹àÌÜ£±£·"                   ,"DATA17"      ,T,500,false,false],
  ["¹àÌÜ£±£¸"                   ,"DATA18"      ,T,500,false,false],
  ["¹àÌÜ£±£¹"                   ,"DATA19"      ,T,500,false,false],
  ["¹àÌÜ£²£°"                   ,"DATA20"      ,T,500,false,false],
  ["¹àÌÜ£²£±"                   ,"DATA21"      ,T,500,false,false],
  ["¹àÌÜ£²£²"                   ,"DATA22"      ,T,500,false,false],
  ["¹àÌÜ£²£³"                   ,"DATA23"      ,T,500,false,false],
  ["¹àÌÜ£²£´"                   ,"DATA24"      ,T,500,false,false],
  ["¹àÌÜ£²£µ"                   ,"DATA25"      ,T,500,false,false],
  ["¹àÌÜ£²£¶"                   ,"DATA26"      ,T,500,false,false],
  ["¹àÌÜ£²£·"                   ,"DATA27"      ,T,500,false,false],
  ["¹àÌÜ£²£¸"                   ,"DATA28"      ,T,500,false,false],
  ["¹àÌÜ£²£¹"                   ,"DATA29"      ,T,500,false,false],
  ["¹àÌÜ£³£°"                   ,"DATA30"      ,T,500,false,false],
  ["¹àÌÜ£³£±"                   ,"DATA31"      ,T,500,false,false],
  ["¹àÌÜ£³£²"                   ,"DATA32"      ,T,500,false,false],
  ["¹àÌÜ£³£³"                   ,"DATA33"      ,T,500,false,false],
  ["¹àÌÜ£³£´"                   ,"DATA34"      ,T,500,false,false],
  ["¹àÌÜ£³£µ"                   ,"DATA35"      ,T,500,false,false],
  ["¹àÌÜ£³£¶"                   ,"DATA36"      ,T,500,false,false],
  ["¹àÌÜ£³£·"                   ,"DATA37"      ,T,500,false,false],
  ["¹àÌÜ£³£¸"                   ,"DATA38"      ,T,500,false,false],
  ["¹àÌÜ£³£¹"                   ,"DATA39"      ,T,500,false,false],
  ["¹àÌÜ£´£°"                   ,"DATA40"      ,T,500,false,false],
  ["¹àÌÜ£´£±"                   ,"DATA41"      ,T,500,false,false],
  ["¹àÌÜ£´£²"                   ,"DATA42"      ,T,500,false,false],
  ["¹àÌÜ£´£³"                   ,"DATA43"      ,T,500,false,false],
  ["¹àÌÜ£´£´"                   ,"DATA44"      ,T,500,false,false],
  ["¹àÌÜ£´£µ"                   ,"DATA45"      ,T,500,false,false],
  ["¹àÌÜ£´£¶"                   ,"DATA46"      ,T,500,false,false],
  ["¹àÌÜ£´£·"                   ,"DATA47"      ,T,500,false,false],
  ["¹àÌÜ£´£¸"                   ,"DATA48"      ,T,500,false,false],
  ["¹àÌÜ£´£¹"                   ,"DATA49"      ,T,500,false,false],
  ["¹àÌÜ£µ£°"                   ,"DATA50"      ,T,500,false,false],
  ["¹àÌÜ£µ£±"                   ,"DATA51"      ,T,500,false,false],
  ["¹àÌÜ£µ£²"                   ,"DATA52"      ,T,500,false,false],
  ["¹àÌÜ£µ£³"                   ,"DATA53"      ,T,500,false,false],
  ["¹àÌÜ£µ£´"                   ,"DATA54"      ,T,500,false,false],
  ["¹àÌÜ£µ£µ"                   ,"DATA55"      ,T,500,false,false],
  ["¹àÌÜ£µ£¶"                   ,"DATA56"      ,T,500,false,false],
  ["¹àÌÜ£µ£·"                   ,"DATA57"      ,T,500,false,false],
  ["¹àÌÜ£µ£¸"                   ,"DATA58"      ,T,500,false,false],
  ["¹àÌÜ£µ£¹"                   ,"DATA59"      ,T,500,false,false],
  ["¹àÌÜ£¶£°"                   ,"DATA60"      ,T,500,false,false],
  ["¹àÌÜ£¶£±"                   ,"DATA61"      ,T,500,false,false],
  ["¹àÌÜ£¶£²"                   ,"DATA62"      ,T,500,false,false],
  ["¹àÌÜ£¶£³"                   ,"DATA63"      ,T,500,false,false],
  ["¹àÌÜ£¶£´"                   ,"DATA64"      ,T,500,false,false],
  ["¹àÌÜ£¶£µ"                   ,"DATA65"      ,T,500,false,false],
  ["¹àÌÜ£¶£¶"                   ,"DATA66"      ,T,500,false,false],
  ["¹àÌÜ£¶£·"                   ,"DATA67"      ,T,500,false,false],
  ["¹àÌÜ£¶£¸"                   ,"DATA68"      ,T,500,false,false],
  ["¹àÌÜ£¶£¹"                   ,"DATA69"      ,T,500,false,false],
  ["¹àÌÜ£·£°"                   ,"DATA70"      ,T,500,false,false],
  ["¹àÌÜ£·£±"                   ,"DATA71"      ,T,500,false,false],
  ["¹àÌÜ£·£²"                   ,"DATA72"      ,T,500,false,false],
  ["¹àÌÜ£·£³"                   ,"DATA73"      ,T,500,false,false],
  ["¹àÌÜ£·£´"                   ,"DATA74"      ,T,500,false,false],
  ["¹àÌÜ£·£µ"                   ,"DATA75"      ,T,500,false,false],
  ["¹àÌÜ£·£¶"                   ,"DATA76"      ,T,500,false,false],
  ["¹àÌÜ£·£·"                   ,"DATA77"      ,T,500,false,false],
  ["¹àÌÜ£·£¸"                   ,"DATA78"      ,T,500,false,false],
  ["¹àÌÜ£·£¹"                   ,"DATA79"      ,T,500,false,false],
  ["¹àÌÜ£¸£°"                   ,"DATA80"      ,T,500,false,false],
  ["¹àÌÜ£¸£±"                   ,"DATA81"      ,T,500,false,false],
  ["¹àÌÜ£¸£²"                   ,"DATA82"      ,T,500,false,false],
  ["¹àÌÜ£¸£³"                   ,"DATA83"      ,T,500,false,false],
  ["¹àÌÜ£¸£´"                   ,"DATA84"      ,T,500,false,false],
  ["¹àÌÜ£¸£µ"                   ,"DATA85"      ,T,500,false,false],
  ["¹àÌÜ£¸£¶"                   ,"DATA86"      ,T,500,false,false],
  ["¹àÌÜ£¸£·"                   ,"DATA87"      ,T,500,false,false],
  ["¹àÌÜ£¸£¸"                   ,"DATA88"      ,T,500,false,false],
  ["¹àÌÜ£¸£¹"                   ,"DATA89"      ,T,500,false,false],
  ["¹àÌÜ£¹£°"                   ,"DATA90"      ,T,500,false,false],
  ["¹àÌÜ£¹£±"                   ,"DATA91"      ,T,500,false,false],
  ["¹àÌÜ£¹£²"                   ,"DATA92"      ,T,500,false,false],
  ["¹àÌÜ£¹£³"                   ,"DATA93"      ,T,500,false,false],
  ["¹àÌÜ£¹£´"                   ,"DATA94"      ,T,500,false,false],
  ["¹àÌÜ£¹£µ"                   ,"DATA95"      ,T,500,false,false],
  ["¹àÌÜ£¹£¶"                   ,"DATA96"      ,T,500,false,false],
  ["¹àÌÜ£¹£·"                   ,"DATA97"      ,T,500,false,false],
  ["¹àÌÜ£¹£¸"                   ,"DATA98"      ,T,500,false,false],
  ["¹àÌÜ£¹£¹"                   ,"DATA99"      ,T,500,false,false]


  SYAKOK="0"
  SYAHO="1"
  KOKUHO="2"

  NYUGAI="0"
  NYUIN="1"
  GAIRAI="2"

  HONNIN    =  "1"
  ROKUSAI   =  "2"
  KAZOKU    =  "3"
  KOREIIPN  =  "4"
  KOREI7    =  "5"
  KOUKIIPN  =  "6"
  KOUKI7    =  "7"
  KOUHI     =  "8"

  RECESBT={ "1111" => [SYAKOK   ,NYUIN,    [1,0,0,0,0],HONNIN  ],
    "1112" => [SYAKOK   ,GAIRAI,   [1,0,0,0,0],HONNIN  ],
    "1113" => [SYAKOK   ,NYUIN,    [1,0,0,0,0],ROKUSAI ],
    "1114" => [SYAKOK   ,GAIRAI,   [1,0,0,0,0],ROKUSAI ],
    "1115" => [SYAKOK   ,NYUIN,    [1,0,0,0,0],KAZOKU  ],
    "1116" => [SYAKOK   ,GAIRAI,   [1,0,0,0,0],KAZOKU  ],
    "1117" => [SYAKOK   ,NYUIN,    [1,0,0,0,0],KOREIIPN],
    "1118" => [SYAKOK   ,GAIRAI,   [1,0,0,0,0],KOREIIPN],
    "1119" => [SYAKOK   ,NYUIN,    [1,0,0,0,0],KOREI7  ],
    "1110" => [SYAKOK   ,GAIRAI,   [1,0,0,0,0],KOREI7  ],
    "1121" => [SYAKOK   ,NYUIN,    [1,1,0,0,0],HONNIN  ],
    "1122" => [SYAKOK   ,GAIRAI,   [1,1,0,0,0],HONNIN  ],
    "1123" => [SYAKOK   ,NYUIN,    [1,1,0,0,0],ROKUSAI ],
    "1124" => [SYAKOK   ,GAIRAI,   [1,1,0,0,0],ROKUSAI ],
    "1125" => [SYAKOK   ,NYUIN,    [1,1,0,0,0],KAZOKU  ],
    "1126" => [SYAKOK   ,GAIRAI,   [1,1,0,0,0],KAZOKU  ],
    "1127" => [SYAKOK   ,NYUIN,    [1,1,0,0,0],KOREIIPN],
    "1128" => [SYAKOK   ,GAIRAI,   [1,1,0,0,0],KOREIIPN],
    "1129" => [SYAKOK   ,NYUIN,    [1,1,0,0,0],KOREI7  ],
    "1120" => [SYAKOK   ,GAIRAI,   [1,1,0,0,0],KOREI7  ],
    "1131" => [SYAKOK   ,NYUIN,    [1,1,1,0,0],HONNIN  ],
    "1132" => [SYAKOK   ,GAIRAI,   [1,1,1,0,0],HONNIN  ],
    "1133" => [SYAKOK   ,NYUIN,    [1,1,1,0,0],ROKUSAI ],
    "1134" => [SYAKOK   ,GAIRAI,   [1,1,1,0,0],ROKUSAI ],
    "1135" => [SYAKOK   ,NYUIN,    [1,1,1,0,0],KAZOKU  ],
    "1136" => [SYAKOK   ,GAIRAI,   [1,1,1,0,0],KAZOKU  ],
    "1137" => [SYAKOK   ,NYUIN,    [1,1,1,0,0],KOREIIPN],
    "1138" => [SYAKOK   ,GAIRAI,   [1,1,1,0,0],KOREIIPN],
    "1139" => [SYAKOK   ,NYUIN,    [1,1,1,0,0],KOREI7  ],
    "1130" => [SYAKOK   ,GAIRAI,   [1,1,1,0,0],KOREI7  ],
    "1141" => [SYAKOK   ,NYUIN,    [1,1,1,1,0],HONNIN  ],
    "1142" => [SYAKOK   ,GAIRAI,   [1,1,1,1,0],HONNIN  ],
    "1143" => [SYAKOK   ,NYUIN,    [1,1,1,1,0],ROKUSAI ],
    "1144" => [SYAKOK   ,GAIRAI,   [1,1,1,1,0],ROKUSAI ],
    "1145" => [SYAKOK   ,NYUIN,    [1,1,1,1,0],KAZOKU  ],
    "1146" => [SYAKOK   ,GAIRAI,   [1,1,1,1,0],KAZOKU  ],
    "1147" => [SYAKOK   ,NYUIN,    [1,1,1,1,0],KOREIIPN],
    "1148" => [SYAKOK   ,GAIRAI,   [1,1,1,1,0],KOREIIPN],
    "1149" => [SYAKOK   ,NYUIN,    [1,1,1,1,0],KOREI7  ],
    "1140" => [SYAKOK   ,GAIRAI,   [1,1,1,1,0],KOREI7  ],
    "1151" => [SYAKOK   ,NYUIN,    [1,1,1,1,1],HONNIN  ],
    "1152" => [SYAKOK   ,GAIRAI,   [1,1,1,1,1],HONNIN  ],
    "1153" => [SYAKOK   ,NYUIN,    [1,1,1,1,1],ROKUSAI ],
    "1154" => [SYAKOK   ,GAIRAI,   [1,1,1,1,1],ROKUSAI ],
    "1155" => [SYAKOK   ,NYUIN,    [1,1,1,1,1],KAZOKU  ],
    "1156" => [SYAKOK   ,GAIRAI,   [1,1,1,1,1],KAZOKU  ],
    "1157" => [SYAKOK   ,NYUIN,    [1,1,1,1,1],KOREIIPN],
    "1158" => [SYAKOK   ,GAIRAI,   [1,1,1,1,1],KOREIIPN],
    "1159" => [SYAKOK   ,NYUIN,    [1,1,1,1,1],KOREI7  ],
    "1150" => [SYAKOK   ,GAIRAI,   [1,1,1,1,1],KOREI7  ],
    "1211" => [SYAHO ,NYUIN,    [0,1,0,0,0],KOUHI ],
    "1212" => [SYAHO ,GAIRAI,   [0,1,0,0,0],KOUHI ],
    "1221" => [SYAHO ,NYUIN,    [0,1,1,0,0],KOUHI ],
    "1222" => [SYAHO ,GAIRAI,   [0,1,1,0,0],KOUHI ],
    "1231" => [SYAHO ,NYUIN,    [0,1,1,1,0],KOUHI ],
    "1232" => [SYAHO ,GAIRAI,   [0,1,1,1,0],KOUHI ],
    "1241" => [SYAHO ,NYUIN,    [0,1,1,1,1],KOUHI ],
    "1242" => [SYAHO ,GAIRAI,   [0,1,1,1,1],KOUHI ],
    "1317" => [SYAKOK   ,NYUIN,    [1,0,0,0,0],KOUKIIPN],
    "1318" => [SYAKOK   ,GAIRAI,   [1,0,0,0,0],KOUKIIPN],
    "1319" => [SYAKOK   ,NYUIN,    [1,0,0,0,0],KOUKI7  ],
    "1310" => [SYAKOK   ,GAIRAI,   [1,0,0,0,0],KOUKI7  ],
    "1327" => [SYAKOK   ,NYUIN,    [1,1,0,0,0],KOUKIIPN],
    "1328" => [SYAKOK   ,GAIRAI,   [1,1,0,0,0],KOUKIIPN],
    "1329" => [SYAKOK   ,NYUIN,    [1,1,0,0,0],KOUKI7  ],
    "1320" => [SYAKOK   ,GAIRAI,   [1,1,0,0,0],KOUKI7  ],
    "1337" => [SYAKOK   ,NYUIN,    [1,1,1,0,0],KOUKIIPN],
    "1338" => [SYAKOK   ,GAIRAI,   [1,1,1,0,0],KOUKIIPN],
    "1339" => [SYAKOK   ,NYUIN,    [1,1,1,0,0],KOUKI7  ],
    "1330" => [SYAKOK   ,GAIRAI,   [1,1,1,0,0],KOUKI7  ],
    "1347" => [SYAKOK   ,NYUIN,    [1,1,1,1,0],KOUKIIPN],
    "1348" => [SYAKOK   ,GAIRAI,   [1,1,1,1,0],KOUKIIPN],
    "1349" => [SYAKOK   ,NYUIN,    [1,1,1,1,0],KOUKI7  ],
    "1340" => [SYAKOK   ,GAIRAI,   [1,1,1,1,0],KOUKI7  ],
    "1357" => [SYAKOK   ,NYUIN,    [1,1,1,1,1],KOUKIIPN],
    "1358" => [SYAKOK   ,GAIRAI,   [1,1,1,1,1],KOUKIIPN],
    "1359" => [SYAKOK   ,NYUIN,    [1,1,1,1,1],KOUKI7  ],
    "1350" => [SYAKOK   ,GAIRAI,   [1,1,1,1,1],KOUKI7  ],
    "1411" => [KOKUHO,NYUIN ,   [1,0,0,0,0],HONNIN  ],
    "1412" => [KOKUHO,GAIRAI,   [1,0,0,0,0],HONNIN  ],
    "1413" => [KOKUHO,NYUIN ,   [1,0,0,0,0],ROKUSAI ],
    "1414" => [KOKUHO,GAIRAI,   [1,0,0,0,0],ROKUSAI ],
    "1415" => [KOKUHO,NYUIN ,   [1,0,0,0,0],KAZOKU  ],
    "1416" => [KOKUHO,GAIRAI,   [1,0,0,0,0],KAZOKU  ],
    "1421" => [KOKUHO,NYUIN ,   [1,1,0,0,0],HONNIN  ],
    "1422" => [KOKUHO,GAIRAI,   [1,1,0,0,0],HONNIN  ],
    "1423" => [KOKUHO,NYUIN ,   [1,1,0,0,0],ROKUSAI ],
    "1424" => [KOKUHO,GAIRAI,   [1,1,0,0,0],ROKUSAI ],
    "1425" => [KOKUHO,NYUIN ,   [1,1,0,0,0],KAZOKU  ],
    "1426" => [KOKUHO,GAIRAI,   [1,1,0,0,0],KAZOKU  ],
    "1431" => [KOKUHO,NYUIN ,   [1,1,1,0,0],HONNIN  ],
    "1432" => [KOKUHO,GAIRAI,   [1,1,1,0,0],HONNIN  ],
    "1433" => [KOKUHO,NYUIN ,   [1,1,1,0,0],ROKUSAI ],
    "1434" => [KOKUHO,GAIRAI,   [1,1,1,0,0],ROKUSAI ],
    "1435" => [KOKUHO,NYUIN ,   [1,1,1,0,0],KAZOKU  ],
    "1436" => [KOKUHO,GAIRAI,   [1,1,1,0,0],KAZOKU  ],
    "1441" => [KOKUHO,NYUIN ,   [1,1,1,1,0],HONNIN  ],
    "1442" => [KOKUHO,GAIRAI,   [1,1,1,1,0],HONNIN  ],
    "1443" => [KOKUHO,NYUIN ,   [1,1,1,1,0],ROKUSAI ],
    "1444" => [KOKUHO,GAIRAI,   [1,1,1,1,0],ROKUSAI ],
    "1445" => [KOKUHO,NYUIN ,   [1,1,1,1,0],KAZOKU  ],
    "1446" => [KOKUHO,GAIRAI,   [1,1,1,1,0],KAZOKU  ],
    "1451" => [KOKUHO,NYUIN ,   [1,1,1,1,1],HONNIN  ],
    "1452" => [KOKUHO,GAIRAI,   [1,1,1,1,1],HONNIN  ],
    "1453" => [KOKUHO,NYUIN ,   [1,1,1,1,1],ROKUSAI ],
    "1454" => [KOKUHO,GAIRAI,   [1,1,1,1,1],ROKUSAI ],
    "1455" => [KOKUHO,NYUIN ,   [1,1,1,1,1],KAZOKU  ],
    "1456" => [KOKUHO,GAIRAI,   [1,1,1,1,1],KAZOKU  ]  }

  FTNKBN={ "1" =>[1,0,0,0,0],
    "5" =>[0,1,0,0,0],
    "6" =>[0,0,1,0,0],
    "B" =>[0,0,0,1,0],
    "C" =>[0,0,0,0,1],
    "2" =>[1,1,0,0,0],
    "3" =>[1,0,1,0,0],
    "E" =>[1,0,0,1,0],
    "G" =>[1,0,0,0,1],
    "7" =>[0,1,1,0,0],
    "H" =>[0,1,0,1,0],
    "I" =>[0,1,0,0,1],
    "J" =>[0,0,1,1,0],
    "K" =>[0,0,1,0,1],
    "L" =>[0,0,0,1,1],
    "4" =>[1,1,1,0,0],
    "M" =>[1,1,0,1,0],
    "N" =>[1,1,0,0,1],
    "O" =>[1,0,1,1,0],
    "P" =>[1,0,1,0,1],
    "Q" =>[1,0,0,1,1],
    "R" =>[0,1,1,1,0],
    "S" =>[0,1,1,0,1],
    "T" =>[0,1,0,1,1],
    "U" =>[0,0,1,1,1],
    "V" =>[1,1,1,1,0],
    "W" =>[1,1,1,0,1],
    "X" =>[1,1,0,1,1],
    "Y" =>[1,0,1,1,1],
    "Z" =>[0,1,1,1,1],
    "9" =>[1,1,1,1,1] }

  KOSORT={ "13" => [true , 1],
           "14" => [true , 2],
           "18" => [true , 3],
           "29" => [true , 4],
           "30" => [true , 5],
           "10" => [false, 6],
           "11" => [false, 7],
           "20" => [false, 8],
           "21" => [false, 9],
           "15" => [false, 10],
           "16" => [false, 11],
           "24" => [false, 12],
           "22" => [false, 13],
           "28" => [false, 14],
           "17" => [false, 15],
           "79" => [false, 16],
           "19" => [false, 17],
           "23" => [false, 18],
           "51" => [false, 19],
           "38" => [false, 20],
           "52" => [false, 21],
           "53" => [false, 22],
           "66" => [false, 23],
           "25" => [false, 24],
           "12" => [false, 25],
  }

  SRYKBN={ "01" => NYUGAI   ,
    "11" => NYUGAI   ,
    "12" => GAIRAI,
    "13" => NYUGAI   ,
    "14" => NYUGAI   ,
    "21" => NYUGAI   ,
    "22" => NYUGAI   ,
    "23" => NYUGAI   ,
    "24" => NYUIN ,
    "25" => GAIRAI,
    "26" => NYUGAI   ,
    "27" => NYUGAI   ,
    "28" => NYUIN ,
    "31" => NYUGAI   ,
    "32" => NYUGAI   ,
    "33" => NYUGAI   ,
    "39" => NYUIN ,
    "40" => NYUGAI   ,
    "50" => NYUGAI   ,
    "54" => NYUGAI   ,
    "60" => NYUGAI   ,
    "70" => NYUGAI   ,
    "80" => NYUGAI   ,
    "90" => NYUIN ,
    "92" => NYUIN ,
    "97" => NYUIN ,
  "99" => NYUGAI    }

  SJKBN = { "01" => "01",
    "02" => "02",
    "03" => "03",
    "04" => "04",
    "05" => "05",
    "06" => "06",
    "07" => "07",
    "50" => "50",
    "51" => "51",
    "52" => "52",
  "90" => "90" }

  PREFCD=["HOKKAIDO"  => "01"],
  ["AOMORI"    => "02"],
  ["IWATE"     => "03"],
  ["MIYAGI"    => "04"],
  ["AKITA"     => "05"],
  ["YAMAGATA"  => "06"],
  ["FUKUSHIMA" => "07"],
  ["IBARAKI"   => "08"],
  ["TOCHIGI"   => "09"],
  ["GUNMA"     => "10"],
  ["SAITAMA"   => "11"],
  ["CHIBA"     => "12"],
  ["TOKYO"     => "13"],
  ["KANAGAWA"  => "14"],
  ["NIIGATA"   => "15"],
  ["TOYAMA"    => "16"],
  ["ISHIKAWA"  => "17"],
  ["FUKUI"     => "18"],
  ["YAMANASHI" => "19"],
  ["NAGANO"    => "20"],
  ["GIFU"      => "21"],
  ["SHIZUOKA"  => "22"],
  ["AICHI"     => "23"],
  ["MIE"       => "24"],
  ["SHIGA"     => "25"],
  ["KYOTO"     => "26"],
  ["OSAKA"     => "27"],
  ["HYOGO"     => "28"],
  ["NARA"      => "29"],
  ["WAKAYAMA"  => "30"],
  ["TOTTORI"   => "31"],
  ["SHIMANE"   => "32"],
  ["OKAYAMA"   => "33"],
  ["HIROSHIMA" => "34"],
  ["YAMAGUCHI" => "35"],
  ["TOKUSHIMA" => "36"],
  ["KAGAWA"    => "37"],
  ["EHIME"     => "38"],
  ["KOCHI"     => "39"],
  ["FUKUOKA"   => "40"],
  ["SAGA"      => "41"],
  ["NAGASAKI"  => "42"],
  ["KUMAMOTO"  => "43"],
  ["OITA"      => "44"],
  ["MIYAZAKI"  => "45"],
  ["KAGOSHIMA" => "46"],
  ["OKINAWA"   => "47"]
end
