#!/usr/bin/ruby

class Receden_common_const

  H250531 = "20130531"

  N = NUMERIC      = 0
  A = ALPHANUMERIC = 1
  K = KANJI        = 2
  T = TEXT         = 3 #(A or K)
  J = KATAKANA     = 4

  #-------------------------------------------------------------------------------
  #   Record Definition
  #-------------------------------------------------------------------------------
  IRrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"          ,"RECID"    ,A, 2 ,true  ,true],
           ["Í½È÷£±"                    ,"YOBI01"   ,N, 1 ,false ,false],
           ["ÅÔÆ»ÉÜ¸©"                  ,"PREFNUM"  ,N, 2 ,true  ,true],
           ["ÅÀ¿ôÉ½"                    ,"TNSNUM"   ,N, 1 ,true  ,true],
           ["°åÎÅµ¡´Ø¥³¡¼¥É"            ,"HOSPCD"   ,N, 7 ,true  ,true],
           ["Í½È÷£²"                    ,"YOBI02"   ,N, 2 ,false ,false],
           ["°åÎÅµ¡´ØÌ¾¾Î"              ,"HOSPNAME" ,K,40 ,false ,true],
           ["ÀÁµáÇ¯·î"                  ,"SKYYM"    ,N, 5 ,true  ,true],
           ["¥Þ¥ë¥Á¥Ü¥ê¥å¡¼¥à¼±ÊÌ¾ðÊó"  ,"MVOLID"   ,N, 2 ,true  ,true],
           ["ÅÅÏÃÈÖ¹æ"                  ,"TEL"      ,A,15 ,false ,false]

  RErecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"                  ,"RECID"                  ,A, 2,true ,true],
           ["¥ì¥»¥×¥ÈÈÖ¹æ"                      ,"RECENUM"                ,N, 6,false,true],
           ["Í½È÷£±"                            ,"YOBI01"                 ,N, 4,false,false],
           ["Í½È÷£²"                            ,"YOBI02"                 ,N, 5,false,false],
           ["Ï«Æ¯¼Ô¤Î»áÌ¾"                      ,"NAME"                   ,T,40,false,true],
           ["ÃË½÷¶èÊ¬"                          ,"SEX"                    ,N, 1,true ,true],
           ["À¸Ç¯·îÆü"                          ,"BIRTHDAY"               ,N, 7,true ,true],
           ["Í½È÷£³"                            ,"YOBI03"                 ,N, 3,false,false],
           ["Æþ±¡Ç¯·îÆü"                        ,"NYUINYMD"               ,N, 7,false,false],
           ["ÉÂÅï¶èÊ¬"                          ,"BTUKBN"                 ,A, 8,false,false],
           ["Í½È÷£´"                            ,"YOBI04"                 ,N, 1,false,false],
           ["Í½È÷£µ"                            ,"YOBI05"                 ,A,10,false,false],
           ["ÉÂ¾²¿ô"                            ,"BEDSU"                  ,N, 4,false,false],
           ["¥«¥ë¥ÆÈÖ¹æÅù"                      ,"PTNUM"                  ,A,20,false,false],
           ["Í½È÷£¶"                            ,"YOBI06"                 ,N, 2,false,false],
           ["Í½È÷£·"                            ,"YOBI07"                 ,N, 1,false,false],
           ["Í½È÷£¸"                            ,"YOBI08"                 ,N, 1,false,false],
           ["Í½È÷£¹"                            ,"YOBI09"                 ,N, 2,false,false],
           ["ÅÅ»»½èÍý¼õÉÕÈÖ¹æ"                  ,"SELNUM"                 ,A,20,false,false],
           ["µ­Ï¿¾ò·ï»ÅÍÍÇ¯·î¾ðÊó"              ,"RECYM"                  ,N, 5,false,false],
           ["ÀÁµá¾ðÊó"                          ,"SKYINF"                 ,A,40,false,false],
           ["¿ÇÎÅ²Ê£±¿ÇÎÅ²ÊÌ¾"                  ,"SRYKA1_CD"              ,N, 2,false,false],
           ["¿ÇÎÅ²Ê£±ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î¿ÍÂÎ¤ÎÉô°ÌÅù","SRYKA1_BUI"             ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£±ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÀ­ÊÌÅù"      ,"SRYKA1_SEX"             ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£±ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î°å³ØÅª½èÃÖ"  ,"SRYKA1_SHOCHI"          ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£±ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÆÃÄê¼ÀÉÂ"    ,"SRYKA1_TOKSIPPEI"       ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£²¿ÇÎÅ²ÊÌ¾"                  ,"SRYKA2_CD"              ,N, 2,false,false],
           ["¿ÇÎÅ²Ê£²ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î¿ÍÂÎ¤ÎÉô°ÌÅù","SRYKA2_BUI"             ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£²ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÀ­ÊÌÅù"      ,"SRYKA2_SEX"             ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£²ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î°å³ØÅª½èÃÖ"  ,"SRYKA2_SHOCHI"          ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£²ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÆÃÄê¼ÀÉÂ"    ,"SRYKA2_TOKSIPPEI"       ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£³¿ÇÎÅ²ÊÌ¾"                  ,"SRYKA3_CD"              ,N, 2,false,false],
           ["¿ÇÎÅ²Ê£³ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î¿ÍÂÎ¤ÎÉô°ÌÅù","SRYKA3_BUI"             ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£³ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÀ­ÊÌÅù"      ,"SRYKA3_SEX"             ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£³ÁÈ¤ß¹ç¤ï¤»Ì¾¾Î°å³ØÅª½èÃÖ"  ,"SRYKA3_SHOCHI"          ,N, 3,false,false],
           ["¿ÇÎÅ²Ê£³ÁÈ¤ß¹ç¤ï¤»Ì¾¾ÎÆÃÄê¼ÀÉÂ"    ,"SRYKA3_TOKSIPPEI"       ,N, 3,false,false]




  RRrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"            ,"RECID"         ,A,  2,true ,true],
           ["²ó¿ô¡ÊÆ±°ì½ýÉÂ¤Ë¤Ä¤¤¤Æ¡Ë"    ,"KAISU"         ,N,  3,false,false],
           ["¶ÈÌ³ºÒ³²¡¦ÄÌ¶ÐºÒ³²¤Î¶èÊ¬"    ,"SAIGAIKBN"     ,N,  1,true ,true],
           ["Ä¢É¼¼ïÊÌ"                    ,"FORMSBT"       ,N,  1,true ,true],
           ["Ç¯¶â¾Ú½ñÈÖ¹æ"                ,"CHOKINUM"      ,N,  9,false,false],
           ["Ï«Æ¯ÊÝ¸±ÈÖ¹æ"                ,"TANKINUM"      ,N, 14,false,false],
           ["½ýÉÂÇ¯·îÆü"                  ,"SHOBYOYMD"     ,N,  7,false,false],
           ["¿··ÑºÆÊÌ"                    ,"SHINKEIKBN"    ,N,  1,true ,true],
           ["Å¾µ¢»öÍ³"                    ,"TENKIKBN"      ,N,  1,true ,true],
           ["ÎÅÍÜ´ü´Ö¡½½éÆü"              ,"RYOSTYMD"      ,N,  7,true ,true],
           ["ÎÅÍÜ´ü´Ö¡½ËöÆü"              ,"RYOEDYMD"      ,N,  7,true ,true],
           ["¿ÇÎÅ¼ÂÆü¿ô"                  ,"JNISSU"        ,N,  3,false,true],
           ["Ï«Æ¯¼Ô¤Î»áÌ¾¡Ê¥«¥Ê¡Ë"        ,"KANANAME"      ,J, 40,false,true],
           ["»ö¶È¤ÎÌ¾¾Î"                  ,"INFO"          ,K, 40,false,false],
           ["»ö¶È¾ì¤Î½êºßÃÏ"              ,"LOCATION"      ,K, 80,false,false],
           ["½ýÉÂ¤Î·Ð²á"                  ,"KEIKA"         ,K,100,false,true],
           ["¾®·×ÅÀ¿ô"                    ,"TENSU"         ,N,  8,false,true],
           ["¾®·×ÅÀ¿ô¶â³Û´¹»»¡Ú¥¤¡Û"      ,"TENSU_KANZAN"  ,N,  9,false,true],
           ["¾®·×¶â³Û¡Ú¥í¡Û"              ,"KINGAKU"       ,N,  9,false,true],
           ["¿©»öÎÅÍÜ¹ç·×²ó¿ô"            ,"SKJKAISU"      ,N,  2,false,false],
           ["¿©»öÎÅÍÜ¹ç·×¶â³Û¡Ú¥Ï¡Û"      ,"SKJKINGAKU"    ,N,  8,false,false],
           ["¹ç·×³Û¡Ú¥¤)¡Ü¡Ú¥í¡Û¡Ü¡Ú¥Ï¡Û" ,"GOKEI"         ,N,  9,false,true]

  SYrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"            ,"RECID"         ,A,  2,true ,true ],
           ["½ýÉÂÌ¾¥³¡¼¥É"                ,"BYOMEICD"      ,N,  7,true ,true ],
           ["¿ÇÎÅ³«»ÏÆü"                  ,"SRYYMD"        ,N,  7,true ,true ],
           ["Í½È÷£±"                      ,"YOBI01"        ,N,  1,false,false],
           ["½¤¾þ¸ì¥³¡¼¥É"                ,"MODCD"         ,A, 80,false,false],
           ["½ýÉÂÌ¾¾Î"                    ,"BYOMEI"        ,K, 40,false,false],
           ["¼ç½ýÉÂ"                      ,"SYUBYO"        ,N,  2,false,false],
           ["ÊäÂ­¥³¥á¥ó¥È"                ,"HSKCOM"        ,K, 40,false,false]

  RIrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"            ,"RECID"            ,A,   2,true ,true ],
           ["¿ÇÎÅ¼±ÊÌ"                    ,"SRYKBN"           ,N,   2,false,false],
           ["¿ÇÎÅ¹Ô°Ù¥³¡¼¥É"              ,"SRYCD"            ,N,   9,true ,true ],
           ["¿ôÎÌ¥Ç¡¼¥¿"                  ,"SURYO"            ,N,   8,false,false],
           ["ÅÀ¿ô"                        ,"TEN"              ,N,   7,false,false],
           ["¶â³Û"                        ,"KINGAKU"          ,N,   7,false,false],
           ["²ó¿ô"                        ,"KAISU"            ,N,   3,false,true],
           ["¥³¥á¥ó¥È¥³¡¼¥É£±"            ,"COMCD1"           ,N,   9,false,false],
           ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£±"        ,"COMMENT1"         ,K, 100,false,false],
           ["¥³¥á¥ó¥È¥³¡¼¥É£²"            ,"COMCD2"           ,N,   9,false,false],
           ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£²"        ,"COMMENT2"         ,K, 100,false,false],
           ["¥³¥á¥ó¥È¥³¡¼¥É£³"            ,"COMCD3"           ,N,   9,false,false],
           ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£³"        ,"COMMENT3"         ,K, 100,false,false],
           ["£±Æü¤Î¾ðÊó"                  ,"DAY01"            ,N,   3,false,false],
           ["£²Æü¤Î¾ðÊó"                  ,"DAY02"            ,N,   3,false,false],
           ["£³Æü¤Î¾ðÊó"                  ,"DAY03"            ,N,   3,false,false],
           ["£´Æü¤Î¾ðÊó"                  ,"DAY04"            ,N,   3,false,false],
           ["£µÆü¤Î¾ðÊó"                  ,"DAY05"            ,N,   3,false,false],
           ["£¶Æü¤Î¾ðÊó"                  ,"DAY06"            ,N,   3,false,false],
           ["£·Æü¤Î¾ðÊó"                  ,"DAY07"            ,N,   3,false,false],
           ["£¸Æü¤Î¾ðÊó"                  ,"DAY08"            ,N,   3,false,false],
           ["£¹Æü¤Î¾ðÊó"                  ,"DAY09"            ,N,   3,false,false],
           ["£±£°Æü¤Î¾ðÊó"                ,"DAY10"            ,N,   3,false,false],
           ["£±£±Æü¤Î¾ðÊó"                ,"DAY11"            ,N,   3,false,false],
           ["£±£²Æü¤Î¾ðÊó"                ,"DAY12"            ,N,   3,false,false],
           ["£±£³Æü¤Î¾ðÊó"                ,"DAY13"            ,N,   3,false,false],
           ["£±£´Æü¤Î¾ðÊó"                ,"DAY14"            ,N,   3,false,false],
           ["£±£µÆü¤Î¾ðÊó"                ,"DAY15"            ,N,   3,false,false],
           ["£±£¶Æü¤Î¾ðÊó"                ,"DAY16"            ,N,   3,false,false],
           ["£±£·Æü¤Î¾ðÊó"                ,"DAY17"            ,N,   3,false,false],
           ["£±£¸Æü¤Î¾ðÊó"                ,"DAY18"            ,N,   3,false,false],
           ["£±£¹Æü¤Î¾ðÊó"                ,"DAY19"            ,N,   3,false,false],
           ["£²£°Æü¤Î¾ðÊó"                ,"DAY20"            ,N,   3,false,false],
           ["£²£±Æü¤Î¾ðÊó"                ,"DAY21"            ,N,   3,false,false],
           ["£²£²Æü¤Î¾ðÊó"                ,"DAY22"            ,N,   3,false,false],
           ["£²£³Æü¤Î¾ðÊó"                ,"DAY23"            ,N,   3,false,false],
           ["£²£´Æü¤Î¾ðÊó"                ,"DAY24"            ,N,   3,false,false],
           ["£²£µÆü¤Î¾ðÊó"                ,"DAY25"            ,N,   3,false,false],
           ["£²£¶Æü¤Î¾ðÊó"                ,"DAY26"            ,N,   3,false,false],
           ["£²£·Æü¤Î¾ðÊó"                ,"DAY27"            ,N,   3,false,false],
           ["£²£¸Æü¤Î¾ðÊó"                ,"DAY28"            ,N,   3,false,false],
           ["£²£¹Æü¤Î¾ðÊó"                ,"DAY29"            ,N,   3,false,false],
           ["£³£°Æü¤Î¾ðÊó"                ,"DAY30"            ,N,   3,false,false],
           ["£³£±Æü¤Î¾ðÊó"                ,"DAY31"            ,N,   3,false,false]


  IYrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"            ,"RECID"            ,A,  2,true ,true],
           ["¿ÇÎÅ¼±ÊÌ"                    ,"SRYKBN"           ,N,  2,false,false],
           ["Í½È÷£±"                      ,"YOBI01"           ,A,  1,false,false],
           ["°åÌôÉÊ¥³¡¼¥É"                ,"SRYCD"            ,N,  9,true ,true],
           ["»ÈÍÑÎÌ"                      ,"SURYO"            ,A, 11,false,false],
           ["ÅÀ¿ô"                        ,"TEN"              ,N,  7,false,false],
           ["²ó¿ô"                        ,"KAISU"            ,N,  3,false,true],
           ["¥³¥á¥ó¥È¥³¡¼¥É£±"            ,"COMCD1"           ,N,  9,false,false],
           ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£±"        ,"COMMENT1"         ,K,100,false,false],
           ["¥³¥á¥ó¥È¥³¡¼¥É£²"            ,"COMCD2"           ,N,  9,false,false],
           ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£²"        ,"COMMENT2"         ,K,100,false,false],
           ["¥³¥á¥ó¥È¥³¡¼¥É£³"            ,"COMCD3"           ,N,  9,false,false],
           ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£³"        ,"COMMENT3"         ,K,100,false,false],
           ["£±Æü¤Î¾ðÊó"                  ,"DAY01"            ,N,  3,false,false],
           ["£²Æü¤Î¾ðÊó"                  ,"DAY02"            ,N,  3,false,false],
           ["£³Æü¤Î¾ðÊó"                  ,"DAY03"            ,N,  3,false,false],
           ["£´Æü¤Î¾ðÊó"                  ,"DAY04"            ,N,  3,false,false],
           ["£µÆü¤Î¾ðÊó"                  ,"DAY05"            ,N,  3,false,false],
           ["£¶Æü¤Î¾ðÊó"                  ,"DAY06"            ,N,  3,false,false],
           ["£·Æü¤Î¾ðÊó"                  ,"DAY07"            ,N,  3,false,false],
           ["£¸Æü¤Î¾ðÊó"                  ,"DAY08"            ,N,  3,false,false],
           ["£¹Æü¤Î¾ðÊó"                  ,"DAY09"            ,N,  3,false,false],
           ["£±£°Æü¤Î¾ðÊó"                ,"DAY10"            ,N,  3,false,false],
           ["£±£±Æü¤Î¾ðÊó"                ,"DAY11"            ,N,  3,false,false],
           ["£±£²Æü¤Î¾ðÊó"                ,"DAY12"            ,N,  3,false,false],
           ["£±£³Æü¤Î¾ðÊó"                ,"DAY13"            ,N,  3,false,false],
           ["£±£´Æü¤Î¾ðÊó"                ,"DAY14"            ,N,  3,false,false],
           ["£±£µÆü¤Î¾ðÊó"                ,"DAY15"            ,N,  3,false,false],
           ["£±£¶Æü¤Î¾ðÊó"                ,"DAY16"            ,N,  3,false,false],
           ["£±£·Æü¤Î¾ðÊó"                ,"DAY17"            ,N,  3,false,false],
           ["£±£¸Æü¤Î¾ðÊó"                ,"DAY18"            ,N,  3,false,false],
           ["£±£¹Æü¤Î¾ðÊó"                ,"DAY19"            ,N,  3,false,false],
           ["£²£°Æü¤Î¾ðÊó"                ,"DAY20"            ,N,  3,false,false],
           ["£²£±Æü¤Î¾ðÊó"                ,"DAY21"            ,N,  3,false,false],
           ["£²£²Æü¤Î¾ðÊó"                ,"DAY22"            ,N,  3,false,false],
           ["£²£³Æü¤Î¾ðÊó"                ,"DAY23"            ,N,  3,false,false],
           ["£²£´Æü¤Î¾ðÊó"                ,"DAY24"            ,N,  3,false,false],
           ["£²£µÆü¤Î¾ðÊó"                ,"DAY25"            ,N,  3,false,false],
           ["£²£¶Æü¤Î¾ðÊó"                ,"DAY26"            ,N,  3,false,false],
           ["£²£·Æü¤Î¾ðÊó"                ,"DAY27"            ,N,  3,false,false],
           ["£²£¸Æü¤Î¾ðÊó"                ,"DAY28"            ,N,  3,false,false],
           ["£²£¹Æü¤Î¾ðÊó"                ,"DAY29"            ,N,  3,false,false],
           ["£³£°Æü¤Î¾ðÊó"                ,"DAY30"            ,N,  3,false,false],
           ["£³£±Æü¤Î¾ðÊó"                ,"DAY31"            ,N,  3,false,false]

  TOrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"            ,"RECID"            ,A,  2,true ,true ],
           ["¿ÇÎÅ¼±ÊÌ"                    ,"SRYKBN"           ,N,  2,false,false],
           ["Í½È÷£±"                      ,"YOBI01"           ,A,  1,false,false],
           ["ÆÃÄê´ïºà¥³¡¼¥É"              ,"SRYCD"            ,N,  9,true ,true ],
           ["»ÈÍÑÎÌ"                      ,"SURYO"            ,A,  9,false,false],
           ["ÅÀ¿ô"                        ,"TEN"              ,N,  7,false,false],
           ["²ó¿ô"                        ,"KAISU"            ,N,  3,false,true],
           ["Ã±°Ì¥³¡¼¥É"                  ,"TANICD"           ,N,  3,false,false],
           ["Ã±²Á"                        ,"TANKA"            ,A, 11,false,false],
           ["ÆÃÄê´ïºàÌ¾¾Î"                ,"NAME"             ,K, 40,false,false],
           ["¾¦ÉÊÌ¾µÚ¤Óµ¬³ÊËô¤Ï¥µ¥¤¥º"    ,"INFO"             ,K,300,false,false],
           ["¥³¥á¥ó¥È¥³¡¼¥É£±"            ,"COMCD1"           ,N,  9,false,false],
           ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£±"        ,"COMMENT1"         ,K,100,false,false],
           ["¥³¥á¥ó¥È¥³¡¼¥É£²"            ,"COMCD2"           ,N,  9,false,false],
           ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£²"        ,"COMMENT2"         ,K,100,false,false],
           ["¥³¥á¥ó¥È¥³¡¼¥É£³"            ,"COMCD3"           ,N,  9,false,false],
           ["¥³¥á¥ó¥ÈÊ¸»ú¥Ç¡¼¥¿£³"        ,"COMMENT3"         ,K,100,false,false],
           ["£±Æü¤Î¾ðÊó"                  ,"DAY01"            ,N,  3,false,false],
           ["£²Æü¤Î¾ðÊó"                  ,"DAY02"            ,N,  3,false,false],
           ["£³Æü¤Î¾ðÊó"                  ,"DAY03"            ,N,  3,false,false],
           ["£´Æü¤Î¾ðÊó"                  ,"DAY04"            ,N,  3,false,false],
           ["£µÆü¤Î¾ðÊó"                  ,"DAY05"            ,N,  3,false,false],
           ["£¶Æü¤Î¾ðÊó"                  ,"DAY06"            ,N,  3,false,false],
           ["£·Æü¤Î¾ðÊó"                  ,"DAY07"            ,N,  3,false,false],
           ["£¸Æü¤Î¾ðÊó"                  ,"DAY08"            ,N,  3,false,false],
           ["£¹Æü¤Î¾ðÊó"                  ,"DAY09"            ,N,  3,false,false],
           ["£±£°Æü¤Î¾ðÊó"                ,"DAY10"            ,N,  3,false,false],
           ["£±£±Æü¤Î¾ðÊó"                ,"DAY11"            ,N,  3,false,false],
           ["£±£²Æü¤Î¾ðÊó"                ,"DAY12"            ,N,  3,false,false],
           ["£±£³Æü¤Î¾ðÊó"                ,"DAY13"            ,N,  3,false,false],
           ["£±£´Æü¤Î¾ðÊó"                ,"DAY14"            ,N,  3,false,false],
           ["£±£µÆü¤Î¾ðÊó"                ,"DAY15"            ,N,  3,false,false],
           ["£±£¶Æü¤Î¾ðÊó"                ,"DAY16"            ,N,  3,false,false],
           ["£±£·Æü¤Î¾ðÊó"                ,"DAY17"            ,N,  3,false,false],
           ["£±£¸Æü¤Î¾ðÊó"                ,"DAY18"            ,N,  3,false,false],
           ["£±£¹Æü¤Î¾ðÊó"                ,"DAY19"            ,N,  3,false,false],
           ["£²£°Æü¤Î¾ðÊó"                ,"DAY20"            ,N,  3,false,false],
           ["£²£±Æü¤Î¾ðÊó"                ,"DAY21"            ,N,  3,false,false],
           ["£²£²Æü¤Î¾ðÊó"                ,"DAY22"            ,N,  3,false,false],
           ["£²£³Æü¤Î¾ðÊó"                ,"DAY23"            ,N,  3,false,false],
           ["£²£´Æü¤Î¾ðÊó"                ,"DAY24"            ,N,  3,false,false],
           ["£²£µÆü¤Î¾ðÊó"                ,"DAY25"            ,N,  3,false,false],
           ["£²£¶Æü¤Î¾ðÊó"                ,"DAY26"            ,N,  3,false,false],
           ["£²£·Æü¤Î¾ðÊó"                ,"DAY27"            ,N,  3,false,false],
           ["£²£¸Æü¤Î¾ðÊó"                ,"DAY28"            ,N,  3,false,false],
           ["£²£¹Æü¤Î¾ðÊó"                ,"DAY29"            ,N,  3,false,false],
           ["£³£°Æü¤Î¾ðÊó"                ,"DAY30"            ,N,  3,false,false],
           ["£³£±Æü¤Î¾ðÊó"                ,"DAY31"            ,N,  3,false,false]

  COrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"            ,"RECID"            ,A,  2,true ,true  ],
           ["¿ÇÎÅ¼±ÊÌ"                    ,"SRYKBN"           ,N,  2,false,false ],
           ["Í½È÷£±"                      ,"YOBI1"            ,A,  1,false,false ],
           ["¥³¥á¥ó¥È¥³¡¼¥É"              ,"SRYCD"            ,N,  9,true ,true  ],
           ["Ê¸»ú¥Ç¡¼¥¿"                  ,"DATA"             ,K, 76,false,false ]

  SJrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"            ,"RECID"            ,A,   2,true ,true ],
           ["¾É¾õ¾Üµ­¶èÊ¬"                ,"SJKBN"            ,N,   2,false,false ],
           ["¾É¾õ¾Üµ­¥Ç¡¼¥¿"              ,"DATA"             ,K,2400,false,false]

  RSrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"            ,"RECID"            ,A, 2,true ,true ],
           ["ÉÂ±¡¡¦¿ÇÎÅ½ê¤Î¶èÊ¬"          ,"HOSPKBN"          ,A, 1,true ,true],
           ["ÀÁµá½ñÄó½ÐÇ¯·îÆü"            ,"SKYYMD"           ,A, 7,true ,true],
           ["ÅÔÆ»ÉÜ¸©Ï«Æ¯¶É¥³¡¼¥É"        ,"PREFCD"          ,N, 2,false,false],
           ["Ï«Æ¯´ð½à´ÆÆÄ½ð¥³¡¼¥É"        ,"OFFICECD"        ,N, 2,false,false],
           ["»ØÄêÉÂ±¡Åù¤ÎÈÖ¹æ"            ,"HOSPCD"           ,N, 7,true ,true ],
           ["Í¹ÊØÈÖ¹æ"                    ,"ZIPCD"            ,N, 7,false,false],
           ["°åÎÅµ¡´Ø½êºßÃÏ"              ,"LOCATION"         ,K,80,false,true ],
           ["°åÎÅµ¡´ØÀÕÇ¤¼Ô»áÌ¾"          ,"NAME"             ,K,40,false,true ],
           ["Ï«ºÒ¿ÇÎÅÈñÃ±²Á"              ,"TANKA"            ,N, 4,true ,true ],
           ["ÀÁµá¶â³Û"                    ,"SKYMONEY"         ,N, 9,false,true ],
           ["ÆâÌõ½ñÅºÉÕËç¿ô"              ,"MAISU"            ,N, 3,false,false],
           ["¥Þ¥ë¥Á¥Ü¥ê¥å¡¼¥à¼±ÊÌ¾ðÊó"    ,"MVOLID"           ,N, 2,true ,true ]

  ETCrecord=["¥ì¥³¡¼¥É¼±ÊÌ¾ðÊó"           ,"RECID"       ,A,2  ,false,false],
            ["¹àÌÜ£°£±"                   ,"DATA01"      ,T,500,false,false],
            ["¹àÌÜ£°£²"                   ,"DATA02"      ,T,500,false,false],
            ["¹àÌÜ£°£³"                   ,"DATA03"      ,T,500,false,false],
            ["¹àÌÜ£°£´"                   ,"DATA04"      ,T,500,false,false],
            ["¹àÌÜ£°£µ"                   ,"DATA05"      ,T,500,false,false],
            ["¹àÌÜ£°£¶"                   ,"DATA06"      ,T,500,false,false],
            ["¹àÌÜ£°£·"                   ,"DATA07"      ,T,500,false,false],
            ["¹àÌÜ£°£¸"                   ,"DATA08"      ,T,500,false,false],
            ["¹àÌÜ£°£¹"                   ,"DATA09"      ,T,500,false,false],
            ["¹àÌÜ£±£°"                   ,"DATA10"      ,T,500,false,false],
            ["¹àÌÜ£±£±"                   ,"DATA11"      ,T,500,false,false],
            ["¹àÌÜ£±£²"                   ,"DATA12"      ,T,500,false,false],
            ["¹àÌÜ£±£³"                   ,"DATA13"      ,T,500,false,false],
            ["¹àÌÜ£±£´"                   ,"DATA14"      ,T,500,false,false],
            ["¹àÌÜ£±£µ"                   ,"DATA15"      ,T,500,false,false],
            ["¹àÌÜ£±£¶"                   ,"DATA16"      ,T,500,false,false],
            ["¹àÌÜ£±£·"                   ,"DATA17"      ,T,500,false,false],
            ["¹àÌÜ£±£¸"                   ,"DATA18"      ,T,500,false,false],
            ["¹àÌÜ£±£¹"                   ,"DATA19"      ,T,500,false,false],
            ["¹àÌÜ£²£°"                   ,"DATA20"      ,T,500,false,false],
            ["¹àÌÜ£²£±"                   ,"DATA21"      ,T,500,false,false],
            ["¹àÌÜ£²£²"                   ,"DATA22"      ,T,500,false,false],
            ["¹àÌÜ£²£³"                   ,"DATA23"      ,T,500,false,false],
            ["¹àÌÜ£²£´"                   ,"DATA24"      ,T,500,false,false],
            ["¹àÌÜ£²£µ"                   ,"DATA25"      ,T,500,false,false],
            ["¹àÌÜ£²£¶"                   ,"DATA26"      ,T,500,false,false],
            ["¹àÌÜ£²£·"                   ,"DATA27"      ,T,500,false,false],
            ["¹àÌÜ£²£¸"                   ,"DATA28"      ,T,500,false,false],
            ["¹àÌÜ£²£¹"                   ,"DATA29"      ,T,500,false,false],
            ["¹àÌÜ£³£°"                   ,"DATA30"      ,T,500,false,false],
            ["¹àÌÜ£³£±"                   ,"DATA31"      ,T,500,false,false],
            ["¹àÌÜ£³£²"                   ,"DATA32"      ,T,500,false,false],
            ["¹àÌÜ£³£³"                   ,"DATA33"      ,T,500,false,false],
            ["¹àÌÜ£³£´"                   ,"DATA34"      ,T,500,false,false],
            ["¹àÌÜ£³£µ"                   ,"DATA35"      ,T,500,false,false],
            ["¹àÌÜ£³£¶"                   ,"DATA36"      ,T,500,false,false],
            ["¹àÌÜ£³£·"                   ,"DATA37"      ,T,500,false,false],
            ["¹àÌÜ£³£¸"                   ,"DATA38"      ,T,500,false,false],
            ["¹àÌÜ£³£¹"                   ,"DATA39"      ,T,500,false,false],
            ["¹àÌÜ£´£°"                   ,"DATA40"      ,T,500,false,false],
            ["¹àÌÜ£´£±"                   ,"DATA41"      ,T,500,false,false],
            ["¹àÌÜ£´£²"                   ,"DATA42"      ,T,500,false,false],
            ["¹àÌÜ£´£³"                   ,"DATA43"      ,T,500,false,false],
            ["¹àÌÜ£´£´"                   ,"DATA44"      ,T,500,false,false],
            ["¹àÌÜ£´£µ"                   ,"DATA45"      ,T,500,false,false],
            ["¹àÌÜ£´£¶"                   ,"DATA46"      ,T,500,false,false],
            ["¹àÌÜ£´£·"                   ,"DATA47"      ,T,500,false,false],
            ["¹àÌÜ£´£¸"                   ,"DATA48"      ,T,500,false,false],
            ["¹àÌÜ£´£¹"                   ,"DATA49"      ,T,500,false,false],
            ["¹àÌÜ£µ£°"                   ,"DATA50"      ,T,500,false,false],
            ["¹àÌÜ£µ£±"                   ,"DATA51"      ,T,500,false,false],
            ["¹àÌÜ£µ£²"                   ,"DATA52"      ,T,500,false,false],
            ["¹àÌÜ£µ£³"                   ,"DATA53"      ,T,500,false,false],
            ["¹àÌÜ£µ£´"                   ,"DATA54"      ,T,500,false,false],
            ["¹àÌÜ£µ£µ"                   ,"DATA55"      ,T,500,false,false],
            ["¹àÌÜ£µ£¶"                   ,"DATA56"      ,T,500,false,false],
            ["¹àÌÜ£µ£·"                   ,"DATA57"      ,T,500,false,false],
            ["¹àÌÜ£µ£¸"                   ,"DATA58"      ,T,500,false,false],
            ["¹àÌÜ£µ£¹"                   ,"DATA59"      ,T,500,false,false],
            ["¹àÌÜ£¶£°"                   ,"DATA60"      ,T,500,false,false],
            ["¹àÌÜ£¶£±"                   ,"DATA61"      ,T,500,false,false],
            ["¹àÌÜ£¶£²"                   ,"DATA62"      ,T,500,false,false],
            ["¹àÌÜ£¶£³"                   ,"DATA63"      ,T,500,false,false],
            ["¹àÌÜ£¶£´"                   ,"DATA64"      ,T,500,false,false],
            ["¹àÌÜ£¶£µ"                   ,"DATA65"      ,T,500,false,false],
            ["¹àÌÜ£¶£¶"                   ,"DATA66"      ,T,500,false,false],
            ["¹àÌÜ£¶£·"                   ,"DATA67"      ,T,500,false,false],
            ["¹àÌÜ£¶£¸"                   ,"DATA68"      ,T,500,false,false],
            ["¹àÌÜ£¶£¹"                   ,"DATA69"      ,T,500,false,false],
            ["¹àÌÜ£·£°"                   ,"DATA70"      ,T,500,false,false],
            ["¹àÌÜ£·£±"                   ,"DATA71"      ,T,500,false,false],
            ["¹àÌÜ£·£²"                   ,"DATA72"      ,T,500,false,false],
            ["¹àÌÜ£·£³"                   ,"DATA73"      ,T,500,false,false],
            ["¹àÌÜ£·£´"                   ,"DATA74"      ,T,500,false,false],
            ["¹àÌÜ£·£µ"                   ,"DATA75"      ,T,500,false,false],
            ["¹àÌÜ£·£¶"                   ,"DATA76"      ,T,500,false,false],
            ["¹àÌÜ£·£·"                   ,"DATA77"      ,T,500,false,false],
            ["¹àÌÜ£·£¸"                   ,"DATA78"      ,T,500,false,false],
            ["¹àÌÜ£·£¹"                   ,"DATA79"      ,T,500,false,false],
            ["¹àÌÜ£¸£°"                   ,"DATA80"      ,T,500,false,false],
            ["¹àÌÜ£¸£±"                   ,"DATA81"      ,T,500,false,false],
            ["¹àÌÜ£¸£²"                   ,"DATA82"      ,T,500,false,false],
            ["¹àÌÜ£¸£³"                   ,"DATA83"      ,T,500,false,false],
            ["¹àÌÜ£¸£´"                   ,"DATA84"      ,T,500,false,false],
            ["¹àÌÜ£¸£µ"                   ,"DATA85"      ,T,500,false,false],
            ["¹àÌÜ£¸£¶"                   ,"DATA86"      ,T,500,false,false],
            ["¹àÌÜ£¸£·"                   ,"DATA87"      ,T,500,false,false],
            ["¹àÌÜ£¸£¸"                   ,"DATA88"      ,T,500,false,false],
            ["¹àÌÜ£¸£¹"                   ,"DATA89"      ,T,500,false,false],
            ["¹àÌÜ£¹£°"                   ,"DATA90"      ,T,500,false,false],
            ["¹àÌÜ£¹£±"                   ,"DATA91"      ,T,500,false,false],
            ["¹àÌÜ£¹£²"                   ,"DATA92"      ,T,500,false,false],
            ["¹àÌÜ£¹£³"                   ,"DATA93"      ,T,500,false,false],
            ["¹àÌÜ£¹£´"                   ,"DATA94"      ,T,500,false,false],
            ["¹àÌÜ£¹£µ"                   ,"DATA95"      ,T,500,false,false],
            ["¹àÌÜ£¹£¶"                   ,"DATA96"      ,T,500,false,false],
            ["¹àÌÜ£¹£·"                   ,"DATA97"      ,T,500,false,false],
            ["¹àÌÜ£¹£¸"                   ,"DATA98"      ,T,500,false,false],
            ["¹àÌÜ£¹£¹"                   ,"DATA99"      ,T,500,false,false]


  NYUGAI="0"
  NYUIN="1"
  GAIRAI="2"

  TANKI="1"
  CHOKI="2"

  SJKBN = { "01" => "01",
    "02" => "02",
    "03" => "03",
    "04" => "04",
    "05" => "05",
    "06" => "06",
    "07" => "07",
    "50" => "50",
    "51" => "51",
    "52" => "52",
  "90" => "90" }

  PREFCD={"HOKKAIDO"  => "01",
          "AOMORI"    => "02",
          "IWATE"     => "03",
          "MIYAGI"    => "04",
          "AKITA"     => "05",
          "YAMAGATA"  => "06",
          "FUKUSHIMA" => "07",
          "IBARAKI"   => "08",
          "TOCHIGI"   => "09",
          "GUNMA"     => "10",
          "SAITAMA"   => "11",
          "CHIBA"     => "12",
          "TOKYO"     => "13",
          "KANAGAWA"  => "14",
          "NIIGATA"   => "15",
          "TOYAMA"    => "16",
          "ISHIKAWA"  => "17",
          "FUKUI"     => "18",
          "YAMANASHI" => "19",
          "NAGANO"    => "20",
          "GIFU"      => "21",
          "SHIZUOKA"  => "22",
          "AICHI"     => "23",
          "MIE"       => "24",
          "SHIGA"     => "25",
          "KYOTO"     => "26",
          "OSAKA"     => "27",
          "HYOGO"     => "28",
          "NARA"      => "29",
          "WAKAYAMA"  => "30",
          "TOTTORI"   => "31",
          "SHIMANE"   => "32",
          "OKAYAMA"   => "33",
          "HIROSHIMA" => "34",
          "YAMAGUCHI" => "35",
          "TOKUSHIMA" => "36",
          "KAGAWA"    => "37",
          "EHIME"     => "38",
          "KOCHI"     => "39",
          "FUKUOKA"   => "40",
          "SAGA"      => "41",
          "NAGASAKI"  => "42",
          "KUMAMOTO"  => "43",
          "OITA"      => "44",
          "MIYAZAKI"  => "45",
          "KAGOSHIMA" => "46",
          "OKINAWA"   => "47" }

  ROSAI_KATAKANA="¡¡" +
                 "¡¼" +
                 "¥¢¥¤¥¦¥¨¥ª¥«¥¬¥­¥®¥¯¥°" +
                 "¥±¥²¥³¥´¥µ¥¶¥·¥¸¥¹¥º¥»¥¼¥½¥¾¥¿¥À" +
                 "¥Á¥Â¥Ä¥Å¥Æ¥Ç¥È¥É¥Ê¥Ë¥Ì¥Í¥Î¥Ï¥Ð" +
                 "¥Ñ¥Ò¥Ó¥Ô¥Õ¥Ö¥×¥Ø¥Ù¥Ú¥Û¥Ü¥Ý¥Þ¥ß" +
                 "¥à¥á¥â¥ä¥æ¥è¥é¥ê¥ë¥ì¥í¥ï" +
                 "¥ò¥ó¥ô"

  FORMSBT={"2" => [NYUIN ,TANKI],
           "3" => [GAIRAI,TANKI],
           "4" => [NYUIN ,CHOKI],
           "5" => [GAIRAI,CHOKI]}

  RECEKA={"01" => "Æâ²Ê",
          "02" => "Àº¿À²Ê",
          "03" => "¿À·Ð²Ê",
          "04" => "¿À·ÐÆâ²Ê",
          "05" => "¸ÆµÛ´ï²Ê",
          "06" => "¾Ã²½´ï²Ê",
          "07" => "°ßÄ²²Ê",
          "08" => "½Û´Ä´ï²Ê",
          "09" => "¾®»ù²Ê",
          "10" => "³°²Ê",
          "11" => "À°·Á³°²Ê",
          "12" => "·ÁÀ®³°²Ê",
          "13" => "ÈþÍÆ³°²Ê",
          "14" => "Ç¾¿À·Ð³°²Ê",
          "15" => "¸ÆµÛ´ï³°²Ê",
          "16" => "¿´Â¡·ì´É³°²Ê",
          "17" => "¾®»ù³°²Ê",
          "18" => "ÈéÉæÈçÇ¢´ï²Ê",
          "19" => "ÈéÉæ²Ê",
          "20" => "ÈçÇ¢´ï²Ê",
          "21" => "À­ÉÂ²Ê",
          "22" => "¤³¤¦Ìç²Ê",
          "23" => "»ºÉØ¿Í²Ê",
          "24" => "»º²Ê",
          "25" => "ÉØ¿Í²Ê",
          "26" => "´ã²Ê",
          "27" => "¼ªÉ¡¤¤¤ó¤³¤¦²Ê",
          "28" => "µ¤´É¿©Æ»²Ê",
          "30" => "Êü¼ÍÀþ²Ê",
          "31" => "Ëã¿ì²Ê",
          "33" => "¿´ÎÅÆâ²Ê",
          "34" => "¥¢¥ì¥ë¥®¡¼²Ê",
          "35" => "¥ê¥¦¥Þ¥Á²Ê",
          "36" => "¥ê¥Ï¥Ó¥ê¥Æ¡¼¥·¥ç¥ó²Ê",
          "37" => "ÉÂÍý¿ÇÃÇ²Ê",
          "38" => "Î×¾²¸¡ºº²Ê",
          "39" => "µßµÞ²Ê" }
end
