SRCS = ORAPI014R1.CBL \
       ORAPI011R1.CBL  \
       ORAPI012R1.CBL  \
       ORAPI012R2.CBL  \
       ORAPI012R3.CBL  \
       ORAPI012R4.CBL  \
       ORAPI101R1.CBL  \
       ORAPI021R1.CBL \
       ORAPI022R1.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

