SRCS = ORCGXA01.CBL \
       ORCGXA99.CBL \
       ORCGXAERR.CBL \
       ORCGXAID1.CBL \
       ORCGXAID2.CBL \
       ORCGXA02.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

