SRCS = \
	ORCL0010.CBL \
	ORCL0011.CBL \
	ORCL0020.CBL \
	ORCL0021.CBL \
	ORCL0030.CBL \
	ORCL0031.CBL \
	ORCL0031N.CBL  \
	ORCL0012.CBL  \

CSRCS = \
	orcuidset.c


top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

