SRCS = ORCGW01.CBL \
       ORCGW02.CBL \
       ORCGW03.CBL \
       ORCGW04.CBL \
       ORCGW05.CBL \
       ORCGW06.CBL \
       ORCGW07.CBL \
       ORCGW08.CBL \
       ORCGW09.CBL \
       ORCGW10.CBL \
       ORCGW11.CBL \
       ORCGW12.CBL \
       ORCGWERR.CBL \
       ORCGWID1.CBL \
       ORCGW13.CBL \
       ORCGW14.CBL \
       ORCGW20SUB01.CBL \
       ORCGW20.CBL \
       ORCGW21.CBL \
       ORCGW22.CBL \
       ORCGW23.CBL \
       ORCGW24.CBL \
       ORCGW25.CBL \
       ORCGW26.CBL \
       ORCGW27.CBL \
       ORCGW28.CBL \
       ORCGW15.CBL \
       ORCGW99.CBL \
       ORCGW98.CBL
        

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

