OBJS = ORCGW01.so   ORCGW02.so   ORCGW03.so   ORCGW04.so   ORCGW05.so  \
       ORCGW06.so   ORCGW07.so   ORCGW08.so   ORCGW09.so   ORCGW10.so  \
       ORCGW11.so   ORCGW12.so   ORCGWERR.so   ORCGWID1.so ORCGW13.so  \
       ORCGW14.so

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global
