# Generated automatically from Makefile.in by configure.
SRCS = ORCGY01.CBL   ORCGY03.CBL   ORCGY04.CBL   ORCGYERR.CBL   ORCHC14.CBL   ORCHC15.CBL

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

