CREATE TABLE tbl_wksryact (
    hospid character(24) NOT NULL,
    nyugaikbn character(1) NOT NULL,
    ptid numeric(10,0) NOT NULL,
    sryka character(2) NOT NULL,
    sryymd character(8) NOT NULL,
    hkncombi numeric(4,0) NOT NULL,
    zainum numeric(8,0) NOT NULL,
    rennum numeric(2,0) NOT NULL,
    drcd character(5),
    srysyukbn character(3),
    srykbn character(2),
    jihimoneytotal numeric(7,0) DEFAULT 0,
    srycd_1 character(9),
    srysuryo_1 numeric(8,3) DEFAULT 0,
    srykaisu_1 numeric(3,0) DEFAULT 0,
    zaikaisu_1 numeric(8,0) DEFAULT 0,
    autokbn_1 character(1),
    inputnum_1 numeric(3,0) DEFAULT 0,
    inputcoment_1 character varying(80),
    inputchi1_1 character(8),
    inputchi1_2 character(8),
    inputchi1_3 character(8),
    inputchi1_4 character(8),
    inputcd_1 character(22),
    jihimoney_1 numeric(7,0) DEFAULT 0,
    srycd_2 character(9),
    srysuryo_2 numeric(8,3) DEFAULT 0,
    srykaisu_2 numeric(3,0) DEFAULT 0,
    zaikaisu_2 numeric(8,0) DEFAULT 0,
    autokbn_2 character(1),
    inputnum_2 numeric(3,0) DEFAULT 0,
    inputcoment_2 character varying(80),
    inputchi2_1 character(8),
    inputchi2_2 character(8),
    inputchi2_3 character(8),
    inputchi2_4 character(8),
    inputcd_2 character(22),
    jihimoney_2 numeric(7,0) DEFAULT 0,
    srycd_3 character(9),
    srysuryo_3 numeric(8,3) DEFAULT 0,
    srykaisu_3 numeric(3,0) DEFAULT 0,
    zaikaisu_3 numeric(8,0) DEFAULT 0,
    autokbn_3 character(1),
    inputnum_3 numeric(3,0) DEFAULT 0,
    inputcoment_3 character varying(80),
    inputchi3_1 character(8),
    inputchi3_2 character(8),
    inputchi3_3 character(8),
    inputchi3_4 character(8),
    inputcd_3 character(22),
    jihimoney_3 numeric(7,0) DEFAULT 0,
    srycd_4 character(9),
    srysuryo_4 numeric(8,3) DEFAULT 0,
    srykaisu_4 numeric(3,0) DEFAULT 0,
    zaikaisu_4 numeric(8,0) DEFAULT 0,
    autokbn_4 character(1),
    inputnum_4 numeric(3,0) DEFAULT 0,
    inputcoment_4 character varying(80),
    inputchi4_1 character(8),
    inputchi4_2 character(8),
    inputchi4_3 character(8),
    inputchi4_4 character(8),
    inputcd_4 character(22),
    jihimoney_4 numeric(7,0) DEFAULT 0,
    srycd_5 character(9),
    srysuryo_5 numeric(8,3) DEFAULT 0,
    srykaisu_5 numeric(3,0) DEFAULT 0,
    zaikaisu_5 numeric(8,0) DEFAULT 0,
    autokbn_5 character(1),
    inputnum_5 numeric(3,0) DEFAULT 0,
    inputcoment_5 character varying(80),
    inputchi5_1 character(8),
    inputchi5_2 character(8),
    inputchi5_3 character(8),
    inputchi5_4 character(8),
    inputcd_5 character(22),
    jihimoney_5 numeric(7,0) DEFAULT 0,
    zaitenkei numeric(8,0) DEFAULT 0,
    zaikaikei numeric(7,0) DEFAULT 0,
    syuten1 numeric(7,0) DEFAULT 0,
    syuten2 numeric(7,0) DEFAULT 0,
    ykzten numeric(7,0) DEFAULT 0,
    kizaiten numeric(7,0) DEFAULT 0,
    douji_denpnum numeric(7,0) DEFAULT 0,
    douji_rennum numeric(1,0) DEFAULT 0,
    contkbn character(1),
    mod_flg numeric(1,0) DEFAULT 0,
    karte_flg numeric(1,0) DEFAULT 0,
    karte_key character varying(36),
    termid character varying(16),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6)
);

ALTER TABLE ONLY tbl_wksryact
    ADD CONSTRAINT tbl_wksryact_primary_key PRIMARY KEY (hospid, nyugaikbn, ptid, sryka, sryymd, hkncombi, zainum, rennum);

