CREATE TABLE "tbl_tensu" (
	"srycd" character(9) NOT NULL,
	"yukostymd" character(8) NOT NULL,
	"yukoedymd" character(8) NOT NULL,
	"srykbn" character(2),
	"srysyukbn" character(3),
	"yukoketa" numeric(2,0) DEFAULT 0,
	"name" character varying(200),
	"kanayukoketa" numeric(2,0) DEFAULT 0,
	"kananame" character varying(200),
	"formalyukoketa" numeric(3,0) DEFAULT 0,
	"formalname" character varying(400),
	"tensikibetu" numeric(1,0) DEFAULT 0,
	"ten" numeric(11,2) DEFAULT 0,
	"tanicd" character(3),
	"tanimojisu" numeric(1,0) DEFAULT 0,
	"taniname" character varying(24),
	"datakbn" numeric(1,0) DEFAULT 0,
	"hkntekkbn" numeric(1,0) DEFAULT 0,
	"nyugaitekkbn" numeric(1,0) DEFAULT 0,
	"routekkbn" numeric(1,0) DEFAULT 0,
	"hospsrykbn" numeric(1,0) DEFAULT 0,
	"osinkbn" numeric(1,0) DEFAULT 0,
	"houksnkbn" numeric(2,0) DEFAULT 0,
	"byokanrenkbn" numeric(2,0) DEFAULT 0,
	"sdokanryo" numeric(2,0) DEFAULT 0,
	"jituday" numeric(1,0) DEFAULT 0,
	"daycnt" numeric(1,0) DEFAULT 0,
	"ykzknrkbn" numeric(1,0) DEFAULT 0,
	"kzmcompsikibetu" numeric(1,0) DEFAULT 0,
	"kzmkgn" numeric(8,0) DEFAULT 0,
	"kzmjgn" numeric(8,0) DEFAULT 0,
	"kzm" numeric(8,0) DEFAULT 0,
	"kzmten" numeric(9,2) DEFAULT 0,
	"kzmerr" numeric(1,0) DEFAULT 0,
	"jgncnt" numeric(3,0) DEFAULT 0,
	"jgncnt1d" numeric(3,0) DEFAULT 0,
	"jgncnt1w" numeric(3,0) DEFAULT 0,
	"jgncntetcm" numeric(2,0) DEFAULT 0,
	"jgncntetc" numeric(3,0) DEFAULT 0,
	"jgncnterr" numeric(1,0) DEFAULT 0,
	"chuksncd" character(4),
	"chuksntsuban" character(1),
	"tsusokuage" numeric(1,0) DEFAULT 0,
	"kgnage" character(2),
	"jgnage" character(2),
	"timeksnkbn" numeric(1,0) DEFAULT 0,
	"kijunteigenkbn" numeric(1,0) DEFAULT 0,
	"kijunteigencd" numeric(3,0) DEFAULT 0,
	"laserksn" numeric(1,0) DEFAULT 0,
	"chpmesuksn" numeric(1,0) DEFAULT 0,
	"micmesuksn" numeric(1,0) DEFAULT 0,
	"knsjiskbn" numeric(1,0) DEFAULT 0,
	"knsjisgrpkbn" numeric(2,0) DEFAULT 0,
	"teigenkbn" numeric(1,0) DEFAULT 0,
	"sekizuisokutei" numeric(1,0) DEFAULT 0,
	"keibujyutu" numeric(1,0) DEFAULT 0,
	"autohougo" numeric(1,0) DEFAULT 0,
	"gaikanrikbn" numeric(1,0) DEFAULT 0,
	"tusokugaikbn" numeric(1,0) DEFAULT 0,
	"hokatuteigenkbn" numeric(3,0) DEFAULT 0,
	"chpnaisiksn" numeric(1,0) DEFAULT 0,
	"autofungo" numeric(1,0) DEFAULT 0,
	"chiikiksn" numeric(1,0) DEFAULT 0,
	"byosyokbn" numeric(1,0) DEFAULT 0,
	"chpgyokosotiksn" numeric(1,0) DEFAULT 0,
	"shortstayope" numeric(1,0) DEFAULT 0,
	"buikbn" numeric(1,0) DEFAULT 0,
	"santeirrkkbn" numeric(1,0) DEFAULT 0,
	"sstkijuncd1" numeric(3,0) DEFAULT 0,
	"sstkijuncd2" numeric(3,0) DEFAULT 0,
	"sstkijuncd3" numeric(3,0) DEFAULT 0,
	"sstkijuncd4" numeric(3,0) DEFAULT 0,
	"sstkijuncd5" numeric(3,0) DEFAULT 0,
	"sstkijuncd6" numeric(3,0) DEFAULT 0,
	"sstkijuncd7" numeric(3,0) DEFAULT 0,
	"sstkijuncd8" numeric(3,0) DEFAULT 0,
	"sstkijuncd9" numeric(3,0) DEFAULT 0,
	"sstkijuncd10" numeric(3,0) DEFAULT 0,
	"ageksnkgn1" character(2),
	"ageksnjgn1" character(2),
	"ageksnsrycd1" character(9),
	"ageksnkgn2" character(2),
	"ageksnjgn2" character(2),
	"ageksnsrycd2" character(9),
	"ageksnkgn3" character(2),
	"ageksnjgn3" character(2),
	"ageksnsrycd3" character(9),
	"ageksnkgn4" character(2),
	"ageksnjgn4" character(2),
	"ageksnsrycd4" character(9),
	"kentaicomment" numeric(1,0) DEFAULT 0,
	"nyukhnkbn" numeric(2,0) DEFAULT 0,
	"nyukhnksnkbn" numeric(3,0) DEFAULT 0,
	"kangoksn" numeric(2,0) DEFAULT 0,
	"oldtenskb" numeric(1,0) DEFAULT 0,
	"oldten" numeric(11,2) DEFAULT 0,
	"madokukbn" numeric(1,0) DEFAULT 0,
	"sinkeihakaikbn" numeric(1,0) DEFAULT 0,
	"seibutugakukbn" numeric(1,0) DEFAULT 0,
	"zoeizaikbn" numeric(1,0) DEFAULT 0,
	"csyyouryo" numeric(5,0) DEFAULT 0,
	"ykzkbn" numeric(1,0) DEFAULT 0,
	"zaigatakbn" numeric(1,0) DEFAULT 0,
	"kouhatukbn" numeric(1,0) DEFAULT 0,
	"longtoyokbn" numeric(1,0) DEFAULT 0,
	"meiuseskb" numeric(1,0) DEFAULT 0,
	"tokukizaiageksnkbn" numeric(1,0) DEFAULT 0,
	"sansokbn" numeric(1,0) DEFAULT 0,
	"tokukizaisbt1" numeric(1,0) DEFAULT 0,
	"tokukizaisbt2" numeric(1,0) DEFAULT 0,
	"jgnten" numeric(7,0) DEFAULT 0,
	"gaitenttlkbn" numeric(3,0) DEFAULT 0,
	"nyutenttlkbn" numeric(3,0) DEFAULT 0,
	"cdkbn_kbn" character(1),
	"cdkbn_syo" numeric(1,0) DEFAULT 0,
	"cdkbn_bu" numeric(2,0) DEFAULT 0,
	"cdkbn_kbnnum" numeric(3,0) DEFAULT 0,
	"cdkbn_kbnnum_eda" numeric(2,0) DEFAULT 0,
	"cdkbn_kouban" numeric(2,0) DEFAULT 0,
	"kokuchi_kbn" character(1),
	"kokuchi_syo" numeric(1,0) DEFAULT 0,
	"kokuchi_bu" numeric(2,0) DEFAULT 0,
	"kokuchi_kbnnum" numeric(3,0) DEFAULT 0,
	"kokuchi_kbnnum_eda" numeric(2,0) DEFAULT 0,
	"kokuchi_kouban" numeric(2,0) DEFAULT 0,
	"kokujiskbkbn1" numeric(1,0) DEFAULT 0,
	"kokujiskbkbn2" numeric(1,0) DEFAULT 0,
	"namechgkbn" numeric(1,0) DEFAULT 0,
	"kananamechgkbn" numeric(1,0) DEFAULT 0,
	"idokanren" character(9),
	"kouhyojyunnum" numeric(9,0) DEFAULT 0,
	"yakkakjncd" character(12),
	"syusaiskb" numeric(1,0) DEFAULT 0,
	"syomeikanren" character(9),
	"chgymd" character(8),
	"haisiymd" character(8),
	"keikasochiymd" character(8),
	"termid" character varying(16),
	"opid" character varying(16),
	"creymd" character(8),
	"upymd" character(8),
	"uphms" character(6),
	Constraint "tbl_tensu_primary_key" Primary Key ("srycd", "yukostymd", "yukoedymd")
);

CREATE INDEX idx_tensu_name ON tbl_tensu USING btree (name);

CREATE INDEX idx_tensu_kananame ON tbl_tensu USING btree (kananame);

CREATE INDEX idx_tensu_kensagrp ON tbl_tensu USING btree (srykbn, knsjisgrpkbn);

COMMENT ON TABLE "tbl_tensu" IS 'ÅÀ¿ô';

