CREATE TABLE "tbl_orderprt" (
	"hospid" character(24) NOT NULL,
	"ptid" numeric(10,0) DEFAULT 0 NOT NULL,
	"ptnum" character(20) NOT NULL,
	"nyugaikbn" character(1) NOT NULL,
	"sryka" character(2) NOT NULL,
	"hkncombi" character(4) NOT NULL,
	"sysymd" character(8) NOT NULL,
	"printymd" character(8) NOT NULL,
	"printhms" character(6) NOT NULL,
	"prtkbn" character(1) NOT NULL,
	"ordernum" numeric(2,0) DEFAULT 0 NOT NULL,
	"rennum" numeric(2,0) DEFAULT 0 NOT NULL,
	"drcd" character(5),
	"srykbn" character(2),
	"srysyukbn" character(3),
	"sryymd" character(8),
	"day1" numeric(3,0) DEFAULT 0,
	"day2" numeric(3,0) DEFAULT 0,
	"day3" numeric(3,0) DEFAULT 0,
	"day4" numeric(3,0) DEFAULT 0,
	"day5" numeric(3,0) DEFAULT 0,
	"day6" numeric(3,0) DEFAULT 0,
	"day7" numeric(3,0) DEFAULT 0,
	"day8" numeric(3,0) DEFAULT 0,
	"day9" numeric(3,0) DEFAULT 0,
	"day10" numeric(3,0) DEFAULT 0,
	"day11" numeric(3,0) DEFAULT 0,
	"day12" numeric(3,0) DEFAULT 0,
	"day13" numeric(3,0) DEFAULT 0,
	"day14" numeric(3,0) DEFAULT 0,
	"day15" numeric(3,0) DEFAULT 0,
	"day16" numeric(3,0) DEFAULT 0,
	"day17" numeric(3,0) DEFAULT 0,
	"day18" numeric(3,0) DEFAULT 0,
	"day19" numeric(3,0) DEFAULT 0,
	"day20" numeric(3,0) DEFAULT 0,
	"day21" numeric(3,0) DEFAULT 0,
	"day22" numeric(3,0) DEFAULT 0,
	"day23" numeric(3,0) DEFAULT 0,
	"day24" numeric(3,0) DEFAULT 0,
	"day25" numeric(3,0) DEFAULT 0,
	"day26" numeric(3,0) DEFAULT 0,
	"day27" numeric(3,0) DEFAULT 0,
	"day28" numeric(3,0) DEFAULT 0,
	"day29" numeric(3,0) DEFAULT 0,
	"day30" numeric(3,0) DEFAULT 0,
	"day31" numeric(3,0) DEFAULT 0,
	"srycd" character(9),
	"srysuryo" numeric(8,3) DEFAULT 0,
	"srysuryo2" numeric(8,3) DEFAULT 0,
	"srykaisu" numeric(3,0) DEFAULT 0,
	"inputcoment" character varying(80),
	"termid" character varying(64),
	"opid" character varying(16),
	"creymd" character(8),
	"upymd" character(8),
	"uphms" character(6),
	Constraint "tbl_orderprt_primary_key" Primary Key ("hospid", "ptid", "ptnum", "nyugaikbn", "sryka", "hkncombi", "sysymd", "printymd", "printhms", "prtkbn", "ordernum", "rennum")
);

COMMENT ON TABLE "tbl_orderprt" IS '¥ª¡¼¥ÀÄ¢É¼';

