SRCS = ORCGKA01.CBL \
       ORCGKAERR.CBL \
       ORCGKAID1.CBL \
       ORCGKAID2.CBL \
       ORCGKA02.CBL \
       ORCGKA021.CBL \
       ORCGKADMY01.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

