SRCS = ORAPI012R1V2.CBL \
       ORAPI011R1V2.CBL  \
       ORAPI014R1V2.CBL  \
       ORAPI012R2V2.CBL  \
       ORAPI012R3V2.CBL \
       ORAPI012R4V2.CBL \
       ORAPI101R1V2.CBL \
       ORAPI021R1V2.CBL \
       ORAPI022R1V2.CBL \
       ORAPI014R2V2.CBL  \
       ORAPI023R1V2.CBL \
       ORAPISUBWKSRY.CBL \
       
top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

